### ISSUE TITLE
Trying to play with dfhack over ssh on linux but its crashes when loading the new world gen & possible fix

### ISSUE THREAD

**Issue by vopi181** [DFHack/dfhack#1015]
Upon looking at my sterrlog.txt, ive found that disabling the scripts in the example config file relating to gui, IE: the modified loading screen etc seems to make it load. Perhaps this is an issue with print_mode on text? I dont know if its related to ssh but i doubt it. Perhaps add the ability to automatically scan our DF config file(init.txt iirc) and see if we have text mode and warn the user about potential stability issues? thanks

**Comment by quietust** [comment]
If you're playing over SSH, you're using [PRINT_MODE:TEXT], so there's probably something that fails to consider the possibility that the DFHack console might not exist.

**Comment by lethosor** [comment]
This worked the last time I checked, although that was probably before 0.42. What DFHack build/architecture are you using?

**Comment by vopi181** [comment]
im using the newest alpha on (the box i sshed into)linux(spec. ubuntu 16.04) 64 bit. Thanks.

**Comment by lethosor** [comment]
I'm assuming you mean 0.43.05-alpha1, since that's the only one with 64-bit support, but it's helpful if you can specify the version. You'd be surprised at how many people think they're using the newest version when they aren't.

I'll try to look into this soon, hopefully in the next couple days (unless someone beats me to it).

**Comment by lethosor** [comment]
I tested briefly on OS X - gui/load-screen works, and worldgen didn't crash for me. It's possible that this is related to some missing offsets on 64-bit Linux, although I don't remember what those are exactly.

Was DFHack crashing on startup? If not, the contents of stderr.log probably aren't as relevant, since those commands would (mostly) have been run on startup. Have you been able to narrow it down to a specific script?

**Comment by vopi181** [comment]
I can try again later, but it seemed to be the following:
#enable gui/extended-status
#view-item-info enable
#gui/load-screen enable
 these seem to be gui related, ill try to downgrade to 32 bit in the meantime.  Also im on 43.05-alpha1. Dwarf fortress crashes when i go to generate a new world. from the main menu i select start new world and it starts loading and displaying alot of ascii characters, it crashes during the ascii character part. Sorry if that doesnt make sense.

**Comment by vopi181** [comment]
it wasn't working at all when i tried again today, but now it worked after doing nothing. Literally tabbed out of the putty session and tabbed back in and it seems to be working. Might be memory related then, huh.

**Comment by lethosor** [comment]
Is this still occurring in alpha3?

**Comment by lethosor** [comment]
I haven't been able to reproduce this in 0.43.05-beta2 on x64 with those 3 scripts enabled. Let me know if you're still able to reproduce it.

**Comment by vopi181** [comment]
nope perfect thanks!

**Comment by lethosor** [comment]
No problem, that's good to know. Thanks!
