### ISSUE TITLE
labormanager pauses on building instruments

### ISSUE THREAD

**Issue by nocico** [DFHack/dfhack#1021]
b-I'ing results in

>LABORMANAGER: Cannot deduce labor for construct building job of type Instrument

patch: https://github.com/DFHack/dfhack/pull/1020

**Comment by lethosor** [comment]
Just a PR is fine in the future (no need to submit an issue after making the PR). Thanks for tracking this down and fixing it!

**Comment by ab9rf** [comment]
Note also that if you can't find a fix, it may be better to open the issue on my fork (https://github.com/ab9rf/dfhack) or at least ping me in the issue because I'm the primary maintainer for labormanager. There are still a few gaps and errors in the labor deducer; I'm fairly certain that some of the forge jobs are wrong, for example.

**Comment by lethosor** [comment]
I'd prefer to have them reported here so it's easier to keep track of for people who aren't watching your fork (at least, I assume you're watching this one), but if it's highly specific to your fork, I don't mind much.
