### ISSUE TITLE
Need 64-bit Allegro libraries for OS X/Linux

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1056]
This is for Stonesense. From http://liballeg.org/a5docs/, Allegro 5.0.11 is available (and currently used on 32-bit OS X, at least), but there's also 5.2.2, which is new. I'm not sure if 5.2.x would work, but it's worth checking.

**Comment by JapaMala** [comment]
I'm using 5.1.12 for the windows build already. As far as I'm aware, there shoudn't be any breaking changes in 5.2.2

**Comment by lethosor** [comment]
OS X is done as of dfhack/stonesense@1925760b2f611d246d1715a2e3cfb591a02ef00b

**Comment by dseguin** [comment]
I'm not sure if it helps, but I was able to get stonesense to compile and run on Debian Linux (64-bit). I just did 3 things:
- Switched stonesense plugin to ON in `plugins/CMakeLists.txt`
- Copied system liballegro libs to `plugins/stonesense/allegro/lib/`
- `Make` was stuck looking for `../plugins/stonesense/proto/../../proto/RemoteFortressReader.pb.cc`, but there is no "proto" dir in `plugins/stonesense/`. Creating an empty "proto" dir fixed it.

The liballegro that ships with Debian Jessie is version [5.0.10-3](https://packages.debian.org/jessie/liballegro5.0).
I'll test it on other distros and report back.

**Comment by lethosor** [comment]
> Make was stuck looking for ../plugins/stonesense/proto/../../proto/RemoteFortressReader.pb.cc, but there is no "proto" dir in plugins/stonesense/. Creating an empty "proto" dir fixed it.

Interesting. This hasn't ever happened for me, but looking at CMakeLists.txt and Plugins.cmake, it looks like it should be looking for `plugins/stonesense/proto/../../proto/RemoteFortressReader.proto`. What CMake version are you using?

**Comment by dseguin** [comment]
> What CMake version are you using?

v3.0.2

**Comment by lethosor** [comment]
Huh, so it's not an issue with 2.x. I guess we should add that folder, then.

Also, feel free to let me know if you have a working allegro build for Linux that we could use.

**Comment by dseguin** [comment]
I just copied over the libs from Debian. Should I submit those?

**Comment by JapaMala** [comment]
If there's a direct link available for pre-compiled binaries that can be
used directly, it might be better to download from there when generating
from cmake, rather than keeping the binaries on the repo, to save space and
clutter.

That's what I did for both of the windows allegro libs, and it works well.

On Mar 22, 2017 11:59 AM, "David Seguin" <notifications@github.com> wrote:

I just copied over the libs from Debian. Should I submit those?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/DFHack/dfhack/issues/1056#issuecomment-288310429>, or mute
the thread

**Comment by dseguin** [comment]
> it might be better to download from there when generating from cmake

You're right, the libs could be downloaded separately. But due to the way linux does package management, they're tucked away in compressed packages. For the [deb package for liballegro](https://packages.debian.org/jessie/liballegro5.0), you would need to download and extract the libs:
```sh
$ wget "http://ftp.us.debian.org/debian/pool/main/a/allegro5/liballegro5.0_5.0.10-3+b1_amd64.deb"
$ ar x "liballegro5.0_5.0.10-3+b1_amd64.deb"
$ tar Jxvf "data.tar.xz"
$ cp /usr/lib/liballegro* </path/to/df/hack/libs/>
```

And the same for [libjpeg](https://packages.debian.org/jessie/libjpeg62-turbo) and [libpng](https://packages.debian.org/jessie/libpng12-0)

**Comment by lethosor** [comment]
@JapaMala there aren't binaries stored in the repo currently (although they might still be on the master branch).

@dseguin this is what we currently use: http://dethware.org/dfhack/download/allegro509b.tar.bz2
I'm not sure if Debian packages more or less than that, but we do need the headers too.

**Comment by dseguin** [comment]
I messed up, it should be the "[-dev](https://packages.debian.org/jessie/liballegro5-dev)" package (http://ftp.us.debian.org/debian/pool/main/a/allegro5/liballegro5-dev_5.0.10-3+b1_amd64.deb) which does have the libs and the headers. So I should add
```sh
$ cp -r /usr/include/ <path/to/dfhack/include/>
```

I'll try adding a part to cmake to do all that.

**Comment by lethosor** [comment]
I'd be wary of downloading directly from a distro package manager, in case that package gets moved or taken down. I suppose we could repackage it (taking out any unnecessary stuff) and upload it to dfhack-bin, though, assuming that doesn't bring any licensing issues into play.

**Comment by dseguin** [comment]
It's [zlib apparently](http://metadata.ftp-master.debian.org/changelogs/main/a/allegro5/allegro5_5.0.10-3_copyright). libjpeg is under [3-clause BSD](http://metadata.ftp-master.debian.org/changelogs/main/libj/libjpeg-turbo/libjpeg-turbo_1.3.1-12_copyright) and libpng is [using it's own license](http://metadata.ftp-master.debian.org/changelogs/main/libp/libpng/libpng_1.2.50-2+deb8u3_copyright).

You're right about the packages maybe being replaced, since the next Debian release is right around the corner. You could get the packages from another distro's repository, but I think they would have the same issues. Should I compile the libs separately?

**Comment by lethosor** [comment]
If you could put some sort of package/archive together, that would be great. I don't think I'll have much time to work on building things for Linux for a couple days. No need to recompile everything if the precompiled libraries are okay to use, though.

**Comment by dseguin** [comment]
I've packaged all the libs and headers in a similar way to http://dethware.org/dfhack/download/allegro509b.tar.bz2 except the root folder is `allegro_x64/` instead of just `allegro/`. I included libpng and libjpeg, and it builds successfully on the few distros I've tested.

Here's the archive: https://github.com/dseguin/dfhack/tree/bin/bin

**Comment by lethosor** [comment]
The root folder name doesn't matter - CMake is now set up (or will be, on Linux) to put the contents of the allegro archive in `stonesense/allegro/linux64/` and strip the root folder from the archive.

**Comment by dseguin** [comment]
Wow, you beat me to it: https://github.com/dseguin/stonesense/commit/a4247b6c440a9ab8e2ef99274fd2f61f2a803534

Where are you putting the binaries?

**Comment by lethosor** [comment]
[Here](https://github.com/DFHack/dfhack-bin/releases/tag/0.43.05) currently.
