### ISSUE TITLE
labormanager not working with some hauling jobs

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1094]
A couple people have reported issues with labormanager not working with hauling non-food items to stockpiles.

**Comment by ab9rf** [comment]
Most likely this is because the person has overcommitted his dwarven population and is asking seven dwarfs to do the work of 70, or 700. labormanager has a priority system for resolving which jobs get assigned to dwarves in this situation. This can be remedied by tweaking priorities with the "labormanager priority" console command, as per the documentation.

Hauling jobs tend to fall behind other jobs because hauling jobs do not get the priority bump for "time since last assigned" that other jobs do. This is because DF internally only generates hauling jobs if there is someone enabled for hauling that type of item (which means labormanager has to always ensure that one dwarf is enabled for all of the hauling categories), and also because it's not always possible to determine which labor a dwarf that is currently doing a hauling job is actually using.

**Comment by ab9rf** [comment]
I contacted the original reporter via reddit, asking for a save that demonstrated this issue, and he reported that he could not replicate the bug.

Closing, for now at least.
