### ISSUE TITLE
create-unit error if called while an announcement popup is shown

### ISSUE THREAD

**Issue by danamlund** [DFHack/dfhack#1109]
Calling create-unit while an popup announcement is awaiting user to "click enter to close window", give an error and leaves dwarf fortress in a pseudo arena-mode state.

Steps to reproduce (from a dfhack console):
1. lua
2. dfhack.gui.showPopupAnnouncement("foo", COLOR_RED)
3. quit
4. modtools/create-unit -race GOBLIN -caste MALE

No goblin is spawned. And I get the following error:
```
/df/hack/scripts/modtools/create-unit.lua:121: Cannot read field viewscreen_dwarfmodest.race: not found.
stack traceback:
        [C]: in metamethod '__index'
        /df/hack/scripts/modtools/create-unit.lua:121: in global 'createUnit'
        /df/hack/scripts/modtools/create-unit.lua:288: in global 'createUnitInCiv'
        /df/hack/scripts/modtools/create-unit.lua:509: in local 'script_code'
        ./hack/lua/dfhack.lua:562: in function 'dfhack.run_script_with_env'
        (...tail calls...)
```

After the error the unit list In dwarf fortress only shows first names of the dwarves.

One fix is to not try to spawn the unit if an announcement popup is shown. But I could not figure out how to check for that. And a minor concern with this fix is how will scripts calling create-unit know whether a unit was spawned.

**Comment by lethosor** [comment]
Oh, one of those popups. I thought you mean a Lua dialog box.

The reason for the "pseudo arena mode" is that create-unit switches into arena mode temporarily to create a unit. The problem is that after it does this, it tries to press 'c' to open the creature creation screen, which doesn't work when a popup announcement is open.

It looks like checking `df.global.world.status.popups` would fix this (it has elements only when a popup announcement is visible). Of course, the script should be changed to actually check that the right screen is open as well.

**Comment by lethosor** [comment]
Okay, I've fixed the issue with popup announcements. I've also improved the script so that any unhandled errors in the future will still restore the original game mode properly.
