### ISSUE TITLE
labormanager shouldn't assign intelligent, grasping pets to labors

### ISSUE THREAD

**Issue by Putnam3145** [DFHack/dfhack#1142]
Partially because they aren't able to be assigned labors any other way (!!) but also because they tend to hold on to axes and picks after being done with their job.

**Comment by ab9rf** [comment]
Can you provide a save? I'd be glad to fix this but I need to know how to exclude such critters from assignment.

**Comment by Putnam3145** [comment]
Yes, [here you go](https://github.com/DFHack/dfhack/files/1202043/labormanagerexample.zip).

**Comment by PatrikLundell** [comment]
The only vanilla intelligent citizen "pets", i.e. Gremlins, can be assigned labors via Dwarf Therapist (though I don't think I've given them tool/uniform jobs since they're really too small for that), so Putnam's comment isn't completely correct. Since DT and Labormanager are not exactly on friendly terms when it comes to labor assignment that might not be important, though. In the somewhat longer term I'd like to see DF fixed so all citizens can be both assigned labors and viewed, however, and if that happens the Labormanager change might need to be re-examined.

**Comment by ab9rf** [comment]
@PatrikLundell The fact that DT can assign labors to a unit by directly manipulating the unit's assigned labors array doesn't make it appropriate to do so. The behavior @Putnam3145 is reporting is a bug and needs to be fixed, and I'll fix it when I find the time... "Other bugs exist" is not a reason not to fix a bug.

**Comment by MurKit** [comment]
Maybe add this as a feature? It'd be fun that dwarves teach some pet to do a simple labor. Just a small dfhack cheat feature.
