### ISSUE TITLE
The widgets.lua List:setChoices trashes the supplied list

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1171]
The operation takes the list of strings supplies and then rehacks it into a list of list that have a string element. That would be perfectly fine if it copied the list first, but it actually trashes the list given to it, which means you can't e.g. use the original list and add elements to it to pass in a new set.
It's reasonably easy to work around it by making sure you always pass a copy of your list to the operation for it to rip apart, but there's no warning label for the unwary, and the operation really ought to do the copying itself (and it isn't really a good idea to create external references to its internal data without a clear warning either).

**Comment by suokko** [comment]
I actually exploited no-copy behavior and made the list read text values every frame from the backing structure using metamods. Is the trashing feature or bug?

**Comment by PatrikLundell** [comment]
Unless it's very clearly documented it's a bug, as there's no reasonable reason to expect it either to use the list passed in for its internal use, nor for it to restructure it.
In my view a version of the function that explicitly uses the list given to it could be created for those who want it (setReferencedChoices?), while the standard version ought to work without weird side effects.

**Comment by lethosor** [comment]
I don't really like the setReferencedChoices name (or idea) much. It's not consistent with other widgets, for one thing, and the name just doesn't make sense to me without context.

Besides, wouldn't adding strings to the input list later fail with the current implementation? You'd have to structure added items the same way as what List uses internally, which isn't necessarily consistent with the original input list. I think setChoices should just copy the table (not sure if we have a table-copying utility function).

@suokko nearly every field in labels (and therefore list entries) can be a function instead of a primitive. See gui/confirm-opts for an example of providing a `pen` callback for list items. I think that should be cleaner than dealing with metamethods to change item properties in most cases.

**Comment by PatrikLundell** [comment]
Adding strings later fails, since the structure has been reworked.
And yes, adding a new operation isn't a good idea. If you want to have direct access to the internals you can achieve that by explicitly accessing the internals. You just have to locate where the reworked structure is anchored and have your manipulator reference that location.

I think the "copyall" function should work to make the copy for this case, although "utils.clone" should be able to do the job as well.

**Comment by suokko** [comment]
@lethosor I agree. There is reason why I choose word 'exploit'. I felt it was wrong but it seemed easiest because I had some trouble propogatting pen and string changes correctly. As code was just a prototype I decided to use metamod hack which was simple. I  wanted to check if there wasn't a surprising reason to take reference instead of built a new table.

**Comment by lethosor** [comment]
I think it's expected that the table passed in won't be used later - e.g. in many cases it's a table literal or something generated/returned by a function. That may not be a reasonable expectation.

Are you able to do the things you want with callbacks in the choice list? e.g.
```lua
{text = function() return tostring(math.random()) end}
```

**Comment by suokko** [comment]
I'm already checking if my fix works with dfhack script. If my own script
breaks it doesn't really matter.

**Comment by PatrikLundell** [comment]
I don't find an expectation that the list would be a throwaway list to be reasonable. After all, the report was generated as a result of attempting to update my list and get that update to be reflected by the table, such as a user adding or removing items to a list.
It's true that in many cases there's a need for an additional list to map selections back to items, but sometimes the strings can be used to do the selection mapping directly.

Since the report was made quite some time ago I don't remember if the trigger was trying to sort an updated list (thus blowing up on comparing strings with the tables the function replaced entries with), or whether setChoices barfed when fed an updated list as it couldn't process its own manipulated list contents.

**Comment by lethosor** [comment]
setChoices can definitely handle the choices it creates.
