### ISSUE TITLE
spotclean doesn't work from the in-game terminal

### ISSUE THREAD

**Issue by alexchandel** [DFHack/dfhack#1194]
Selecting a tile with `k` and attempting to run `spotclean` with the in-game terminal, [command-prompt](https://dfhack.readthedocs.io/en/stable/docs/Plugins.html#id232), fails with the following error:

```
Could not invoke spotclean: unsuitable UI state.
```

Typing `spotclean` into the actual command prompt succeeds, naturally. It seems like the presence of the in-game command prompt is incorrectly recognized as an unsuitable UI state.

**Comment by lethosor** [comment]
Well, it is recognized as an unsuitable UI state, but that's not necessarily "incorrect", because command-prompt is implemented as a separate screen. As far as DFHack can tell, there's no difference between running `spotclean` from command-prompt and running it from DF's "unit preferences" screen when a tile is selected a few screens below.

**Comment by alexchandel** [comment]
Can it be taught to recognize it? Other commands like `teleport` seem to work from it, & even understand where the cursor is/which unit is selected.
