### ISSUE TITLE
buildings_other_id needs to be updated

### ISSUE THREAD

**Issue by carterscottm** [DFHack/dfhack#1196]
Some tiles are showing incorrect graphics as mentioned in the below issue from the DFGraphics repo.  It was indicated on that issue that some building IDs have changed in 0.44 and need to be updated in DFHack.

https://github.com/DFgraphics/Phoebus/issues/10

**Comment by lethosor** [comment]
It's building_other_id - looks like a new vector was added to world.buildings.other: https://github.com/DFHack/df-structures/commit/56b101086f761445e84a4251f4f74907d4d9340d#diff-162906ce2ae57b77b86860a8968419d4L376

**Comment by aikoncwd** [comment]
Nice, any way to compile this to test it?

**Comment by lethosor** [comment]
It *is* compiled - that's what's in DFHack 0.44.02-alpha1 right now. The issue is that the IDs that are used to index that list of vectors was not updated, so world.buildings.other.SHOP actually contains wagons, for example. I've found the ID that should be added (DISPLAY_CASE), so there should be a fix available soon. Once it is, you can [compile DFHack](https://dfhack.readthedocs.io/en/latest/docs/Compile.html) to test it (or wait for another [pre]release).

**Comment by lethosor** [comment]
From https://github.com/DFHack/dfhack/issues/1202#issuecomment-353513030:
> For the record, [this] bug also affects the scripts "autofarm.rb" and "gui/extended-status.lua", as well as the plugins "autogems" and "power-meter".
