### ISSUE TITLE
exportlegends doesn't work from open-legends

### ISSUE THREAD

**Issue by devenv** [DFHack/dfhack#1241]
Documentation says that it should work.
What I did: `ctrl-shift-p` `open-legends`, opens fine, `ctrl-shift-p` (ctrl-a does nothing, not sure what it should do, documentation is incomplete) `exportlegends all`, I get an error `Exportlegends must be run from the main legends view`.
Latest df (0.44.07), latest dfhack (0.44.07-alpha1-Linux-64-gcc-7)

**Comment by lethosor** [comment]
The script probably doesn't work from command-prompt. Try the DFHack console instead.

Also, I assume "0.44.06-alpha1-Linux-64-gcc-7" should be 0.44.07, because DFHack for 0.44.06 doesn't work with DF 0.44.07.

As for the documentation, it says that Ctrl-A is bound to `exportlegends all` in the `legends` screen. `open-legends` makes its own screen, so that binding won't work there. I'm not sure how to make the documentation more complete, but feel free to make suggestions.

**Comment by devenv** [comment]
Yeah, missed a buttong there, fixed.
It works from console, thanks! :)
Documentation:
* `exportlegends all` binding section I would add `(incompatible with open-legends)`
* `open-legends` section I would add `(use console)`... or something :)

**Comment by lethosor** [comment]
The keybindings in the documentation are automatically generated from dfhack.init-example. I could add a note on open-legends, or fix the exportlegends keybinding to work with it too.

**Comment by lethosor** [comment]
Does this work in 0.44.12-r1? #1319 might have fixed this too.

**Comment by devenv** [comment]
Yep, works in 0.44.12, thanks :)
