### ISSUE TITLE
fpause doesn't effect the Creating A New Region screen

### ISSUE THREAD

**Issue by moonheart08** [DFHack/dfhack#1256]
Exactly what it says on the tin. creating a region can quickly become hard to control, so having a way to fpause it as well would be ***awesome***.

**Comment by lethosor** [comment]
fpause only controls the global "pause_state" variable, which is ignored in world generation. There are other ways we could affect it (e.g. forcing a screen to appear that does nothing), but even then, the unresponsiveness during worldgen is due to DF only reading input occasionally, which also affects when DFHack can do something like that. In other words, you can pause worldgen by running something like command-prompt, but it won't be any more responsive than pressing Enter/Esc in-game.

**Comment by lethosor** [comment]
Done (only committed a week or so late)
