### ISSUE TITLE
manipulator: Extraneous "(dfhack)" label in UI.

### ISSUE THREAD

**Issue by kindaro** [DFHack/dfhack#1389]
When `manipulator` is enabled, there is a corresponding option added to unit list. It currently reads: `Manage labors (DFHack)`. I propose that we shorten that to `Manage labors`.

Motivation:
* Breaks immersion. _(This is the main reason I bring it up for discussion.)_
* Adds visual noise.
* Other plugins do not label their added options with `DFHack`.
* Options added by DFHack plugins are traditionally marked with red hot key reminders, as opposed to the usual green of vanilla DF, so there is no need for an extra label.

If there is consensus, I can make the _(trivial)_ pull request.

**Comment by lethosor** [comment]
It was one of the first tools (possibly even the first) to draw to existing DF screens at all, so that's probably the reason for the `(DFHack)` part. Since I've seen some people who don't realize this is DFHack-provided despite the `(DFHack)` label, I think removing that part would only lead to more confusion - it's not taking up a lot of space. Also, red vs. green might not be obvious for anyone color-blind.

@quietust might have more input, as he's the original author of manipulator.

**Comment by kindaro** [comment]
Alright! I will close the issue then!

**Comment by warmist** [comment]
Also note: [Lua api](https://dfhack.readthedocs.io/en/stable/docs/Lua%20API.html#screen-api) first warning in that section says that: "As a matter of policy, in order to avoid user confusion, all interface screens added by dfhack should bear the “DFHack” signature." However this is not enforced very much so reverse issue could be made :D

**Comment by lethosor** [comment]
That's referring to the "DFHack" indicator drawn in the lower border of the screen itself - that's enforced by default for at least all Lua screens (that is, the base class draws the indicator), and possibly C++ ones that use drawBorder() or something similar. Manipulator has a similar indicator on the screen, but the issue here is about the option to open that screen from the unit list screen.
