### ISSUE TITLE
Autofarm is not managing barley

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#1421]
It looks like autofarm is not managing or seeing barley at all. In fact, it disables farms that I have manually set to grow barley. Setting a threshold manually does not help. Looking into it, it seems to be because `df.ui.tasks.discovered_plants` is returning false for barley, though I'm not sure why. This is with 0.44.12-r2 on Win10 64 bit. Can anyone reproduce? I can provide a save file if needed.

**Comment by lethosor** [comment]
Do you actually have barley seeds? Is barley showing up in the seeds menu for an above-ground farm plot?

**Comment by ab9rf** [comment]
The Ruby version of autofarm is badly broken for surface crops; it cannot tell which seeds are plantable and which are not. 

I rewrote autofarm as a C++ plugin a while back (https://github.com/ab9rf/dfhack/tree/autofarm-cpp), but that code has not yet been merged into a release (indeed, I haven't even open a PR for it yet). 

My work on this from last August was working as far as I can recall, but I never got around to finishing it up or submitting a PR. I don't recall why I didn't submit a PR for it, but the fact that I didn't suggests that there was still some work to be done it it. I just don't recall what.

In any case, I am not going to allocate energy to fixing the old Ruby autofarm script; the C++ plugin is in every way superior, and should probably replace the script at the earliest opportunity.

**Comment by TV4Fun** [comment]
@lethosor, yes I do have barley seeds and it is showing up as plantable for an above-ground farm plot.

**Comment by lethosor** [comment]
Tested this in a fort I have in 0.44.12. discovered_plants does indeed contain 0 for barley, despite barley being an available option. A few others I tested (asparagus, single-grain wheat) were 1 or 0 according to whether they appeared in the farm plot list or not. I don't actually know what I'm talking about here, but autofarm.cpp [also uses discovered_plants](https://github.com/ab9rf/dfhack/blob/autofarm-cpp/plugins/devel/autofarm.cpp#L190), so it might have a similar issue.

At any rate, since I don't know much about this tool, I'll defer to @ab9rf's judgement above.

**Comment by ab9rf** [comment]
It may be worth exploring whether filtering the plant list by `discovered_plants` is an appropriate choice. It may also be that there's some other weird thing going on with barley specifically, although I can't imagine what that would be. (There is nothing in barley's raws that suggest it should receive special treatment.)

**Comment by ab9rf** [comment]
This issue will be mooted by #1468

**Comment by lethosor** [comment]
Closing as fixed in #1468
