### ISSUE TITLE
features magma doesn't work

### ISSUE THREAD

**Issue by epsilon-phase** [DFHack/dfhack#1516]
With current git head on develop branch and the current version(0.47.04-alpha0-28-ga2e34a3b), features magma does not successfully reveal a magma feature.

**Comment by lethosor** [comment]
@epsilon-phase is this on Windows? If so, it's likely the same cause as #1519

**Comment by epsilon-phase** [comment]
@lethosor 
No, it's on linux 64 bit(which I guess is the only flavor of linux these days)

Features actually fails to produce anything and spits out this error.

```
...wnloads/df_47_04_linux/df_linux/hack/scripts/feature.lua:36: attempt to index a nil value (local 'feat')
stack traceback:
	...wnloads/df_47_04_linux/df_linux/hack/scripts/feature.lua:36: in global 'list_features'
	...wnloads/df_47_04_linux/df_linux/hack/scripts/feature.lua:76: in local 'script_code'
	./hack/lua/dfhack.lua:680: in function 'dfhack.run_script_with_env'
	(...tail calls...)
```

Since I originally posted it I've been keeping the build up to date, and there's been no resolution thus far.

**Comment by epsilon-phase** [comment]
This is currently working :) 

:3

**Comment by lethosor** [comment]
Wait, did you change something? `feature.lua` hasn't changed since 2018, so the only reason I can think of for the error you provided is that your save had a null feature somewhere. Did you move to a new save?

Also, we provide 32-bit Linux builds too (for 32-bit Linux DF, available [here](http://www.bay12games.com/dwarves/older_versions.html)), and alignment issues are frequently *not* cross-platform. Specifically, #1519 is only an issue on Windows - on Linux and macOS, world.arena_spawn is aligned properly.

**Comment by epsilon-phase** [comment]
@lethosor No, that's a good question, but when I did update suddenly it showed up on the map that it hadn't previously(It didn't work on *any* map).

Last commit I have pulled is 63f774dfef3001625b6f6b41f51a57cbc33f52ec

None of the things look promising as to *how* it got fixed. I'll look at my other saves  in the meantime and report back
