### ISSUE TITLE
Segfault on 0.47.03-beta1

### ISSUE THREAD

**Issue by ror6ax** [DFHack/dfhack#1521]
```
./dfhack: line 83: 103134 Segmentation fault      (core dumped) setarch "$setarch_arch" -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"
```
How do I upload more data for debugging? Error logs are empty.

**Comment by ragundo** [comment]
If you have a RelWithDbgInfo version of DFHack, start it and attach gdb/Visual Studio or whatever debugger you use to the process.

**Comment by lethosor** [comment]
We didn't release a 0.47.03-rc1 - can you double-check what build you're using?
When does this segfault occur? Is it reproducible?

**Comment by erikjuvan** [comment]
Hello, since the issue is open, I also seem to be having similiar issues, so I thought I would pitch in.
My system:
`Linux arch 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux`
`Dwarffortress v0.47.04`
`DFHack version 0.47.04-alpha0` - built from AUR

Segfault happenes in plugins/stonesense/ItemConfiguration.cpp on line `if(contentLoader->itemConfigs[main_type] == nullptr)` because `itemConfigs` seems to be empty. 

Also the last text that is displayed before it hangs is: `Loading stonesense/items/greiger items/Grei_items.xml`

Also the logs (stderr.log and stdout.log) are empty.

**Comment by lethosor** [comment]
@erikjuvan does that happen when you launch Stonesense or when you start DF (or something else)?

**Comment by erikjuvan** [comment]
@lethosor I run `./dfhack`, and from the dfhack console I then run `stonesense`, before "start playing" or after (doesn't matter).

**Comment by lethosor** [comment]
Your issue might be https://github.com/DFHack/stonesense/issues/68, then

**Comment by lethosor** [comment]
@ror6ax we're going to need more details to address this - first off, does it occur in 0.47.04-beta1 or newer? If so, is it reproducible? Is it specific to any save (if so, uploading it would help)? What architecture (32-bit or 64-bit) are you using?

**Comment by lethosor** [comment]
We're going to need more information to be able to reproduce/fix this, unfortunately. Feel free to reopen this if it's reproducible in >=0.47.04.

**Comment by shawntan** [comment]
Just tested this on 0.47.04, same thing happens for me, stops at:

`Loading stonesense/items/greiger items/Grei_items.xml`

**Comment by lethosor** [comment]
Could you add details on the Stonesense crash to https://github.com/DFHack/stonesense/issues/68? The initial report here is likely unrelated.
