### ISSUE TITLE
Can't run Ruby scripts when the DF path contains non-ASCII characters

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1549]
Unsure if this is Windows-specific
Forum reports:
http://www.bay12forums.com/smf/index.php?topic=164123.msg8037202#msg8037202
http://www.bay12forums.com/smf/index.php?topic=164123.msg8125163#msg8125163

Related to #1099, #1146

**Comment by lethosor** [comment]
I was unable to reproduce on Linux with unicode characters in the DF path, a custom script path, and within the script itself, so this appears to be Windows-specific.

**Comment by PatrikLundell** [comment]
Replicated LordBalkan's problem on Windows 10.1, 64 bit:

´´´E: Encoding::ConverterNotFoundError: code converter not found (ASCII-8BIT to UTF-8)
 eval:1:in `require'
 eval:1:in `<main>'
TWBT: version 6.xx
TWBT: set PRINT_MODE to TWBT in data/init/init.txt to activate the plugin
E: NoMethodError: undefined method `onstatechange' for DFHack:Module
 eval:1:in `<main>'
E: NoMethodError: undefined method `onstatechange' for DFHack:Module
 eval:1:in `<main>'
multilevel is not a recognized command.
DFHack is ready. Have a nice day!
DFHack version 0.47.04-beta1 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]#
´´´
when changing "Games" to "Gãmes" in the path.  The TwbT stuff is irrelevant, of course. I've stopped using it again (due to crashes that may or may not have been related to TwbT).

**Comment by lethosor** [comment]
Interesting, I'll try some other characters on Linux. Could you try running `type startdwarf` in the broken setup and see if that gives you the correct path?

**Comment by PatrikLundell** [comment]
Interesting... I changed the path, started the pyLNP console, and launched DF without problem. Killed it and started DF from the DF directory directly and it complained. In that state, typing "startdwarf" before anything is launched results in this (after the stuff above):
´´´
[DFHack]# startdwarf
E: Encoding::ConverterNotFoundError: code converter not found (ASCII-8BIT to UTF-8)
 eval:2:in `load'
 eval:2:in `block in <main>'
 eval:2:in `catch'
 eval:2:in `<main>'
[DFHack]#
´´´

**Comment by lethosor** [comment]
@PatrikLundell I meant run the command `type startdwarf`, which should give you the path to the script (instead of running it). I'm curious if that's the part that's breaking.
(The `type` command is taken from bash; maybe we should come up with another name that's less confusing...)

**Comment by PatrikLundell** [comment]
´´´
[DFHack]# type startdwarf
startdwarf is a Ruby script: C:\Gπmes\Dwarf Fortress\Dwarf Fortress 47_04 Starter Pack r01\Dwarf Fortress 0.47.04/hack/scripts/startdwarf.rb
´´´

**Comment by lethosor** [comment]
I had forgotten that I had script paths set up so that all of the scripts were being located in ../../dfhack/scripts. But even after removing that and adding an `ã` to my DF path, I was unable to reproduce the issue (on Linux).
Potentially related: We bundle Ruby 2.0.0 on win64, but Ruby 1.8.7 everywhere else (except on osx64, where we fall back to the system-provided Ruby, which should be 2.x these days).

**Comment by lethosor** [comment]
I tried Ruby 2.7 on Linux. Scripts still seem to work, but when the directory contains ã, it complains about the error handling:

ASCII only:
```
[DFHack]# multicmd foo;bar
foo is not a recognized command.
bar is not a recognized command.
```

With ã:
```
[DFHack]# multicmd foo;bar
E: SyntaxError: eval:2: syntax error, unexpected local variable or method, expecting ']'
catch(:script_finished) { load '.....
^~~~~

foo is not a recognized command.
bar is not a recognized command.
```
