### ISSUE TITLE
Exportlegends "-1" values as default

### ISSUE THREAD

**Issue by ralpha** [DFHack/dfhack#1554]
This talks about the [exportlegends.lua](https://github.com/DFHack/scripts/blob/master/exportlegends.lua) script.
I have noticed that everywhere in `<historical_event>` where there is a value that is:
- unknown
- does not exist
- does not apply
- ...

It will default to giving it a value of "-1". In some cases this gives some weird results.
Here some examples:
```
<historical_event>
        <id>430</id>
        <type>artifact_created</type>
        <artifact_id>4</artifact_id>
        <creator_unit_id>-1</creator_unit_id>
        <creator_hfid>730</creator_hfid>
        <site>-1</site>
        <circumstance>
                <type>-1</type>
        </circumstance>
        <reason>
                <type>none</type>
        </reason>
</historical_event>
```
or
```
<historical_event>
        <id>2870</id>
        <type>change_hf_state</type>
        <hfid>1437</hfid>
        <state>1</state>
        <reason>-1</reason>
        <site>-1</site>
</historical_event>
```

As you can see this adds a lot of "Redundant" tags for things that should be the default value.
In the case of `reason.type` the default value is `none` instead of `-1`.

These events could be shorter:
```
<historical_event>
        <id>430</id>
        <type>artifact_created</type>
        <artifact_id>4</artifact_id>
        <creator_hfid>730</creator_hfid>
</historical_event>
```
or
```
<historical_event>
        <id>2870</id>
        <type>change_hf_state</type>
        <hfid>1437</hfid>
        <state>1</state>
</historical_event>
```
But this of course might break old implementations.

What should/should not happen with these tags? Are there some guild-lines that we should look to when making these decisions?

**Comment by PatrikLundell** [comment]
Much of the exportlegends script is using a brute force approach, i.e. it reads all fields and generates a tag from the field name and inserts the contents of the field within those tag entries. This means the script doesn't "know" that the field is an enum, nor that -1 "means" don't know/don't care/...

It's possible for the script to detect that it's dealing with an enum and insert the enum value, but that causes the script to blow up every time it encounters an enum value that hasn't been mapped. It's probably possible to detect that an enum value isn't mapped and insert the numeric value instead, but that's not implemented currently (and ought to be made as a utility function in the script if used, rather than implemented separately in each location). I guess a utility function could check if the lower case converted enum string matches "none" and suppress generation in that case, but then it would have to be fed the tag string and generate both tags plus the data or nothing, and it would also have to be fed the number of indents to use.
Suppressing tags when the value is -1 as a general measure will probably cause the script to behave incorrectly for a number of cases. I think there are enums where -1 is an actual value (together with -2 and -3), and you wouldn't want a Values element to be removed just because the value happens to be -1 (marginally negative, on a scale of -100 .. 100, I think).

For the parts that are hand coded to match the data it's dealing with, suppression of "no info" tags would be preferred (and I think it's done in some places). It can be noted that Toady has some cases of optional elements in his XML export (there are cases of combined start/end tags with no data where the tag name conveys the info).

Note that this is my opinion, not any kind of "official" stand point.

**Comment by lethosor** [comment]
> It's possible for the script to detect that it's dealing with an enum and insert the enum value, but that causes the script to blow up every time it encounters an enum value that hasn't been mapped. It's probably possible to detect that an enum value isn't mapped and insert the numeric value instead, but that's not implemented currently (and ought to be made as a utility function in the script if used, rather than implemented separately in each location).

I'm pretty sure the `df_enums` pseudo-table in exportlegends does this, actually (it prints "unknown N" if N is an unknown value instead of breaking). Maybe not all things use it, though.

**Comment by PatrikLundell** [comment]
The big one, i.e. the default for history event elements, just outputs tostring(v), and I know I reverted at least one case I'd made of using "naïve" enum value outputs because of the risk of breaking.

The general history element case can probably be dealt with by checking if it's an enum, and the case I implemented can be changed to use the wrapper function.

If ref-target can be reached from Lua it would be possible to write something that suppressed lines containing null values for at least the major ones (by checking if the ref-target value is one in a defined set when the value is -1).

**Comment by lethosor** [comment]
Exposing ref-target to Lua is a work in progress, hopefully for r2: #1543 

Can you give an example of tostring() breaking? It should work on `nil`, which is what accessing an undefined enum item returns:
```
[lua]# ~tostring(df.item_type.FOO)
nil
```

**Comment by PatrikLundell** [comment]
I thought ref-target was a work in progress, but not ready yet, so yes, we'll have to wait a little more.

tostring doesn't break, but "<X>"..df.item_type [object.X].."</X>" does, which is what the naïve output tried to do (and I think your example would produce a number on a match, not "FOO"?).

Thus, my attempt at at an enum output is not directly related to the current default output method of a number, which we'd want to improve to show the enum value instead when applicable (which we can do. I think I'll make an attempt tomorrow to see what happens). Sorry for the confusion created.
