### ISSUE TITLE
deathcause not working on corpses

### ISSUE THREAD

**Issue by ctempleton3** [DFHack/dfhack#1563]
I got teh following error message with deatcause. i don't 

```
[DFHack]# deathcause
E: NoMethodError: undefined method `item' for #<DFHack::UiLookList_TItems:0x00018b4cb986c8>
 C:/Users/ctemp/Desktop/DWARFF~1/PERIDE~2.04-/Dwarf Fortress 0.47.04/hack/ruby/item.rb:25:in `item_find'
 hack/scripts/deathcause.rb:44:in `<top (required)>'
 eval:2:in `load'
 eval:2:in `block in <main>'
 eval:2:in `catch'
 eval:2:in `<main>'
```

If i do a type deatcause I get the following.

```
[DFHack]# type deathcause
deathcause is a Ruby script: C:\Users\ctemp\Desktop\DWARFF~1\PERIDE~2.04-\Dwarf Fortress 0.47.04/hack/scripts/deathcause.rb
```

I don't see any characters in the whole path that are unicode. so I don't think it is that.

`C:\Users\ctemp\Desktop\Dwarf Fortress\PeridexisErrant's Starter Pack 0.47.04-r04\Dwarf Fortress 0.47.04\hack\scripts`

Can somebody help me with this?

**Comment by lethosor** [comment]
Looks like the ui_look_list changes we made didn't get applied to the Ruby module that deathcause uses. If you change line 25 of hack/ruby/item.rb from "k.item" to "k.data.Item", that should fix it (make sure you get the capitalization right!).

As far as I can tell, this only breaks when you have a corpse selected. If you select the unit in the `u`nits screen, deathcause should work in that case (so that could work as an alternative to modifying the file I mentioned for now).
