### ISSUE TITLE
search: normalize non-ASCII characters when matching

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1598]
Search strings are already normalized to lowercase, so searching for "dumat" will match "Dumat Timnärbomrek". Since DF doesn't really offer options for typing special characters on keyboards without them, it would be nice if "timnar" (a instead of ä) would also match.
(This should probably be added to MiscUtils or something for ease of use in other plugins.)

**Comment by GitOnUp** [comment]
I've noticed that at least the LinuxDwarfPack I'm running seems to have altered the raws so that they're normalized *there* rather than normalizing them in the search mechanism, which might serve as a mitigating solution for many.

**Comment by lethosor** [comment]
Yeah, I think there's at least one mod out there for that. Some tilesets might also do that so they can change the accented characters to additional symbols without them appearing in names.

**Comment by GitOnUp** [comment]
I've been looking into how this might be done.

For context, there are some glyphs in the tilesets (like the AE ligature) which I haven't seen appearing in raws files by default, but which reasonably could in a mod.  IIRC it's also possible for someone really into world building to use TWBT and repurpose otherwise graphical-only indices in the tileset for other ligatures or accents in a `-text` tileset.

My initial attempt at this replaces characters as per my best guess coming from looking at the curses tileset, but given the possibility of customization and possible issues with translations to other languages I'm leaning towards having a configuration file approach that can defaulted to an English version based on my best guesses.

**Comment by lethosor** [comment]
Oh, I hadn't even thought of Æ/æ, but I suppose converting it to "AE" for comparison purposes is fine. I don't see any other characters on the [wiki](https://dwarffortresswiki.org/index.php/Character_table) that this would apply to.

As for mods: DF uses an existing standard code page (CP437), where characters and symbols are already defined. If mods *add* non-ASCII alphabetic characters (or change existing ones), my opinion is that they're asking for trouble and we don't need to spend too much time supporting that. (As an extreme example, a mod that swaps the tiles for 'a' (97) and 'b' (98) would already break a variety of text-based filters, including in vanilla DF.) My impression is that most mods that don't strictly follow CP437 are removing alphabetic characters, so that would hopefully not be an issue. It could be worth making configurable down the road, and may be more necessary if DF supports more tiles in the next release, but I wouldn't spend too much time on that now.

**Comment by GitOnUp** [comment]
Ah perfect, I was looking for a table like that.  Alright, I'll look at modifying based on that.
