### ISSUE TITLE
zone enumerates nicknames on assign

### ISSUE THREAD

**Issue by ajs** [DFHack/dfhack#1709]
As you can see here:

![image](https://user-images.githubusercontent.com/98660/99208114-9c3c4680-278d-11eb-8829-c0f529689fd8.png)

the zone command set nicknames for all of my animals that are numbers. Here is what I did:

Select the first zone with "i" and then, in the console:

```
[DFHack]# zone set
Target building type: pen/pasture or pit.
Current building set to #10471
[DFHack]# zone assign all own not egglayer not grazer not race DOG not race CAT tame
No building id specified. Will use #10471
Process all units.
Filter: 'own civilization'
Filter: 'not egglayer'
Filter: 'not grazer'
Filter: 'not race of DOG'
Filter: 'not race of CAT'
Filter: 'tame'
Default filter for assign: 'not merchant'; use 'merchant' filter to override.
Matched creatures: 25
Processed creatures: 25
```

Then repeat this for the other two pens with:
```
[DFHack]# zone assign all own egglayer not grazer not race DOG not race CAT tame
...
Matched creatures: 13
Processed creatures: 13
```

and

```
[DFHack]# zone assign all own not egglayer grazer not race DOG not race CAT tame
...
Matched creatures: 49
Processed creatures: 49
```

Seems like it should have worked, but all of my creatures are where they started (not the pens I assigned them to) and are now nicknamed with integers.

**Comment by ajs** [comment]
Also note that I brought this up [on reddit](https://old.reddit.com/r/dwarffortress/comments/juwmps/biweekly_df_questions_thread/gcg33k5/) but have not yet gotten any feedback there.

I'm running LNP on Windows: PeridexisErrant's Starter Pack 0.47.04-r10

**Comment by lethosor** [comment]
What version of DFHack are you using?

**Comment by lethosor** [comment]
Ah, I think I found an issue with #1652 that would cause this. Working on a fix.

**Comment by lethosor** [comment]
Thanks for the report! Turned out to be a simple fix. It'll be in 0.47.04-r4. If you want a fixed plugin that works with r3, you can get it from https://buildmaster.lubar.me/executions/execution-in-progress?executionId=598020 when it's done (or the latest automated build from https://dfhack.org/builds/ if that link doesn't work by the time you see it). In your case, you would want to download "Windows64.zip", then extract `zone.plug.dll` from it and overwrite the existing file of the same name in hack/plugins with the new one.

**Comment by ajs** [comment]
Wow, thanks @lethosor that was amazingly fast!
