### ISSUE TITLE
autodump, automelt, autotrade: ability to disable announcements

### ISSUE THREAD

**Issue by Areephe** [DFHack/dfhack#1782]
i need version of this plugins without anouncements, plz help

**Comment by myk002** [comment]
Why do you need versions without announcements? That's how they communicate that they're working. There are already a number of announcement filter programs. Do they not meet your needs?

**Comment by Areephe** [comment]
you about announcements window utility from PyLNP? I want disable "market dump 1 item" 100 hundred times on in-game announcements "a" window

**Comment by lethosor** [comment]
We don't distribute slightly-modified versions of plugins for things like this, because that would cause a lot of confusion. We *could* make these announcements configurable, though, and #212 is an existing similar request for some other plugins.

It doesn't look like these announcements can be filtered natively by DF (i.e. they don't correspond to a category in `announcements.txt`) so your best bet currently would be using a third-party tool to filter announcements, like myk002 mentioned.

It would also be possible to modify a personal copy of these plugins, if you're able to [compile DFHack from source](https://docs.dfhack.org/en/stable/docs/Compile.html) (although this is a bit harder on Windows than on other platforms). The plugins all appear to be pretty similar, so two options could be:
* commenting out the `showAnnouncement` calls, or
* changing `DELTA_TICKS` to a larger value to make the plugins check for stockpile changes less frequently

**Comment by myk002** [comment]
This looks like a good candidate to move status messages to the Debug logging framework. Then they can be filtered with configuration in dfhack.init

**Comment by lethosor** [comment]
Does that support directing output to in-game announcements? I'm not sure how important it is to preserve that feature, if people rely on it for status updates (the messages are well-intentioned but can be excessive)

**Comment by myk002** [comment]
Ah, no it does not.  I was going back through the issue list and Debug.h was on my mind. I failed to appreciate that this was referring to announcements, not log messages.  Does anyone care about the announcements? Maybe we can just move them to log messages..
