### ISSUE TITLE
blueprint plugin: issues with walls and coords

### ISSUE THREAD

**Issue by TristramGoose** [DFHack/dfhack#1794]
Hello, I may be using the blueprints wrong but the y coordinate seems to be inverted if it goes off a coordinates grid. 
So (1,15) becomes (1,-15). Also, I can't get it to record constructed walls and floors in the blueprints. 
I am using dwarf fortress 0.47.05 with dfhack 0.47.05-r1. The tileset used is taffer. 

Here are the commands I used. The blueprint output is in the top left. 
![image](https://user-images.githubusercontent.com/30111689/110249562-a18fed80-7f44-11eb-9be5-9f71ffc745c6.png)

Here is the building blue print lacking the constructed walls I placed for testing purposes in one of the bedrooms.  
![image](https://user-images.githubusercontent.com/30111689/110249602-e1ef6b80-7f44-11eb-9106-57ac09002e56.png)

**Comment by lethosor** [comment]
What happens if you leave out the commas in the commands you're running? I don't think those are necessary, and they might be causing issues.

I'm also not sure how the blueprint in your second screenshot could produce the output in the first screenshot (specifically, the screenshot appears to be the output of a different blueprint that produces dig designations instead of placing furniture). If you have the blueprint files you're using, could you upload them instead? That would be easier than trying to recreate the issue from a screenshot, although a screenshot of the issue would still be useful.

I see you're also using a combination of `blueprint` and `quickfort` - is there a reason for this? `quickfort` should be a drop-in replacement in most cases, but if there's something it can't handle, definitely let us know. We're trying to move over to quickfort in the long term.

**Comment by TristramGoose** [comment]
Hello Lethosor, I will try your suggestions. The 2nd image was the output of the first image when I used blueprint. I think the d and b's stand for doors and beds. I was using both quickfort and blueprint because I was trying to capture an existing build for use in other forts. I'm guessing quickfort can do both instead? I will look into that.

**Comment by TristramGoose** [comment]
The commas didn't made a difference in the outcome. Here is an image of the blueprint command run and the generated files. The files had to be uploaded to github as xlsx as csv isn't supported.  I made my blueprint copy of a wooden building from the center of the room with a different items in each quadrant to make it easier to identify which way things were copied. 
[building-build.xlsx](https://github.com/DFHack/dfhack/files/6098011/building-build.xlsx)
[building-dig.xlsx](https://github.com/DFHack/dfhack/files/6098012/building-dig.xlsx)
[building-place.xlsx](https://github.com/DFHack/dfhack/files/6098013/building-place.xlsx)
[building-query.xlsx](https://github.com/DFHack/dfhack/files/6098014/building-query.xlsx)
![Command and Copied build](https://user-images.githubusercontent.com/30111689/110255957-5685d280-7f64-11eb-9418-c999765c31fd.PNG)

**Comment by lethosor** [comment]
Oh, sorry! I think I was thinking of `fortplan` - I didn't realize you were trying to *produce* a blueprint. Thanks for providing the files, and I'll try to take a look.

**Comment by myk002** [comment]
I plan to overhaul the blueprint plugin, which should fix this issue. Might take a few months, though, since I'm focused right now on writing automated tests for quickfort
