### ISSUE TITLE
In-game command-prompt: DF will detect key input and change zoom level

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#1855]
When using DFHack's command-prompt (default Ctrl-Shift-P), DF will detect certain key inputs and use them. I have zoom in/out set to [ and ]. Typing them in causes DF to resize tiles.

Not sure what the possibility or desirability of such a fix is, but I thought I'd mention it.

**Comment by quietust** [comment]
It looks like those keys are being checked directly inside `interfacest::loop()` (see "g_src" in the Linux version), and most noticeably they are done *before* the input is fed to the currently active viewscreen; as such, there's no way we can prevent those keys from being handled.

The same would also apply to the following keys:
* OPTIONS
* MOVIES
* HELP
* PREFIX (and STRING_A048 thru STRING_A057 while active)
* TOGGLE_TTF
* ZOOM_IN, ZOOM_OUT, and ZOOM_RESET
* RECORD_MACRO, PLAY_MACRO, SAVE_MACRO, and LOAD_MACRO

From the looks of it, the only keys we _can_ intercept are TOGGLE_FULLSCREEN, FPS_UP, and FPS_DOWN

**Comment by lethosor** [comment]
Viewscreens do have a `key_conflict()` method that allows screens to prevent DF from handling certain "special" keys like the ones above, but DF only ever calls it for the first 3 keys in the list above (OPTIONS, MOVIES, HELP). For OPTIONS, this allows screens to determine whether `Esc` should show the options menu. `MOVIES` and `HELP` can be blocked to allow screens with text fields to accept the `;` and `?` keys without opening another screen. This is similar to what you're looking for, but we can't block any of the other keys in the list above, possibly because none of them are bound to alphanumeric keys by default.

In fact, most text entries appear to be impacted by this, including DF's own. I tried adding your `[` `]` keybindings and renaming a building with `Ctrl+n`, and entering either of those keys as part of the building name zooms in/out.

I don't think there's much we can do on the DFHack side, unfortunately. Maybe we can do something complicated at the SDL layer, but it wouldn't be easy.
