### ISSUE TITLE
Keybindings sometimes act as if Alt is stuck down

### ISSUE THREAD

**Issue by ShimmerFairy** [DFHack/dfhack#1878]
As of commit 2fc5fbacb5bdf7183d61045a4786d58571081eec (though the problem showed up in earlier commits), I've noticed that some keybindings don't respect the Alt modifier. All of the keybindings I've tested are part of the default configuration.

For reference, I'm playing on 64-bit Linux, DF version 0.47.05

A list of problems I've noted:

* `Alt-I` (for gui/unit-info-viewer) will trigger when you hit `I` in the `v` screen, which conflicts with the inventory screen. Luckily DF also receives the input, so backing out of the DFHack screen will leave you looking at the inventory screen.
* `Alt-R` (for gui/room-list) will trigger when you hit `r` when making a bedroom out of a bed. As before, DF also receives the input, so backing out takes you to the expected room-building menu.
* `Alt-F1` (for hotkeys) will trigger on `F1`. Unlike the other two, DF won't receive the input, and so won't zoom to the location F1 is supposed to.

It seems that hitting `Alt` at all will suddenly require use of the Alt key again, and alt-tabbing away from the game brings the problem back again. Between the alt-tab and the extra `Alt` keypress, you can use these commands without `Alt` as often as you want.  My guess is that DFHack is seeing the Alt of the alt-tab and holding on to it when it shouldn't.

**Comment by lethosor** [comment]
What window manager / desktop environment are you using?

> My guess is that DFHack is seeing the Alt of the alt-tab and holding on to it when it shouldn't.

That sounds like exactly what #468 and #485 fixed. Are you using a custom libgraphics build? What version of SDL are you using?

For reference, I cannot reproduce this issue on Ubuntu+GNOME on 2fc5fbacb5bdf7183d61045a4786d58571081eec after alt-tabbing out of and back into DF, so I'm suspecting a system-specific issue at this point, unfortunately.

**Comment by ShimmerFairy** [comment]
I'm using Plasma. I've not done any funny business with libgraphics, and as for SDL I've got 1.2.15 and 2.0.14 (don't know if you need legacy SDL or the current one, so there's both). I should also note I didn't have this issue in the past, when using DFHack on previous versions of the game.

**Comment by lethosor** [comment]
Thanks. DF uses SDL 1.2 currently (hopefully that changes soon). Any recent Plasma upgrades/changes on your end, by chance?

Can you run `devel/modstate-monitor start`, keep the DFHack console visible, and reproduce the issue? I'm specifically interested in what it reports for "alt" when the issue occurs. On my end, I see `alt=1` printed when I press down `Alt`, then `alt=0` as soon as I press `Tab`. `alt=1` doesn't show up again until I press `Alt` again when the DF window has focus. Let me know what happens on your end.

**Comment by ShimmerFairy** [comment]
Sorry for the late response. I update Plasma (along with the rest of my Gentoo system) pretty frequently, so I can't usefully report what version, if any, causes issues. I've recently upgraded to Plasma 5.22.2, where the problem still exists (I have not compiled a new version of DFHack since the bug report, however).

Using modstate-monitor, I find that the `alt=0` does not show up after an alt-tab, unlike what you observe. Pressing Ctrl or Shift after going back to DF prints `alt=1` with every change in the other keys' state. Pressing down Alt again does *not* generate a new line with `alt=1`, but it does (as expected) print an `alt=0` line when the key is released.

**Comment by lethosor** [comment]
Hm, doesn't sound like there's much we can do on our end, unfortunately. It sounds like DF simply isn't receiving the "Alt key released" event, which both DF and DFHack rely on. I'm curious about a couple things, although these won't really help us narrow down a solution:

* You mentioned `Alt-i` as one key combination that gives you trouble. What happens if you rebind the "d"esignations menu to `Alt-i`? (This is under `Key bindings > Dwarf mode > Main: Designations` - no need to delete the `d` binding, and no need to save your changes.) Specifically, if you alt-tab out and in, does pressing `i` reliably open the zones menu or the designations menu?
* You mentioned that older DF+DFHack versions worked previously as expected - do they work _now_ with your current desktop environment? A clean install of an old DF version you remember playing as well as DFHack for that version should be enough to determine this.
* What does `devel/modstate-monitor` indicate if you hold down `Alt` and click outside of the DF window, or cause it to lose focus in some other way? (Not sure how well this will work with your window manager, or if it's possible - hopefully it doesn't cause issues, at least.)

**Comment by ShimmerFairy** [comment]
So I've tested the first two points, and here's what I found:

* Altering the keybindings for Dwarf Fortress show no issue with alt-tab screwing things up. This is the case both for commands that would conflict with others (`Alt-i` conflicting with `i` for zones), and for commands that wouldn't do anything (I used `Alt-y` since there's no `y` command in the top level). It does not matter if I'm running dfhack or not, Dwarf Fortress itself handles key commands with `Alt` exactly as expected.
* Running older versions of DF + DFHack (the oldest being DF 0.47.02) that I don't recall having any keybinding conflicts with shows that the issue does exist. It's possible my memory's imperfect though, or that I just managed to dodge the issue before. I played these old versions on a much older computer where, if I wanted to run DF, it basically had to be the only thing open, so I was probably far less likely to alt-tab back then.

Overall, I would say that the issue is with DFHack, since Dwarf Fortress itself does not exhibit the issue, and I've yet to encounter a single other application with problems. It's possible that some change in the window manager or other lower-level software happened to break DFHack's specific way of picking up input, but I suspect the fix would still have to be in DFHack and not that other software.

**Comment by lethosor** [comment]
We actually have access to DF's source code for how it handles modifier keys, and that's where our fix in #485 came from, so I still feel that it's a DF, SDL, and/or window manager issue (especially given the fact that I can't reproduce it on Linux).

DF: https://github.com/svenstaro/dwarf_fortress_unfuck/blob/a6f59cfc4f8fbe7e211d7c9d3113e8c83d723877/g_src/enabler_input.cpp#L224-L256

DFHack: https://github.com/DFHack/dfhack/blob/22a0b62e4317eb8ee046014186e627ea63ad6142/library/Core.cpp#L2481-L2490

I did notice that there is some extra modifier key handling [here](https://github.com/svenstaro/dwarf_fortress_unfuck/blob/a6f59cfc4f8fbe7e211d7c9d3113e8c83d723877/g_src/enabler_input.cpp#L458-L478) (on DF's side) but I'm not sure what it does.

Are you able to [compile DFHack](https://docs.dfhack.org/en/latest/docs/Compile.html)? If so, I would be interested in seeing what key-release events happen [here](https://github.com/DFHack/dfhack/blob/22a0b62e4317eb8ee046014186e627ea63ad6142/library/Core.cpp#L2483) when you alt-tab out of the DF window (specifically in the case where DF/DFHack isn't recognizing the "Alt released" event).

**Comment by myk002** [comment]
I can reproduce this reliably. I is strange that the alt key only appears stuck on some screens. on the designations menu, for example, `m` toggles marker mode and the `alt-m` DFHack addition toggles box select. Alt-tabbing out, refocusing the DF window with the mouse, and hitting `m` still toggles marker mode.

However, when in the `u`nit viewscreen, `alt-i` shows the unit info screen (and just `i` does nothing). After alt-tabbing out of DF and refocusing the DF window, just `i` will bring up the unit info screen. You can `ESC` back out and hit `i` again to bring it up. after manually tapping `alt`, `i` just means `i` again and does not bring up the unit info screen.

So the issue is just for hotkeys?

I'll instrument `Core.cpp` and see what I can find.

I'm also on KDE on Gentoo, FWIW.

**Comment by myk002** [comment]
The `showkey` utility (package sys-apps/kbd-2.4.0) shows the release of the alt key getting delivered

**Comment by lethosor** [comment]
Does `alt-i` have some special KDE functionality? For instance, on macOS, `alt-e` and `alt-u` can be used to type accents and umlauts, respectively, and those can occasionally cause issues with SDL. I can't think of another good reason off the top of my head why this would only affect certain keys in combination with Alt.

Incidentally, on revisiting the [code path](https://github.com/svenstaro/dwarf_fortress_unfuck/blob/a6f59cfc4f8fbe7e211d7c9d3113e8c83d723877/g_src/enabler_input.cpp#L458-L478) in libgraphics I mentioned last time, it looks like that might affect what happens when a modifier key is pressed/released when other keys are also pressed at the same time.

**Comment by myk002** [comment]
`alt-i` doesn't mean anything specific that I know of, and I can reproduce this with any of the `alt-*` bindings in `dfhack.init`  I don't think it's only affecting certain keys. I think it's affecting the dfhack keybinding resolution path. DF's idea of alt state appears to differ from DFHack's when alt-tab is used to switch window focus.

it does look like the code you linked to "forces" keyup for modifier keys. do we need to copy that code into our handler path?

**Comment by lethosor** [comment]
Oh, I think I misinterpreted your `h` and `alt-h` comment as meaning that `h` didn't cause issues, but in that case, both are DF bindings.

Referring to the segment [here](https://github.com/svenstaro/dwarf_fortress_unfuck/blob/a6f59cfc4f8fbe7e211d7c9d3113e8c83d723877/g_src/enabler_input.cpp#L458-L478), I don't see how it could be something we need yet. As far as I can tell, the issue is that we never receive an "alt up" event (per `devel/modstate-monitor`), and therefore cannot update our copy of "modstate". DF *uses* its copy of "modstate" in several places, including the linked code path, but only *updates* it [here](https://github.com/svenstaro/dwarf_fortress_unfuck/blob/a6f59cfc4f8fbe7e211d7c9d3113e8c83d723877/g_src/enabler_input.cpp#L455), before any processing, which is very similar to [our update logic](https://github.com/DFHack/dfhack/blob/22a0b62e4317eb8ee046014186e627ea63ad6142/library/Core.cpp#L2481-L2490).

There could definitely be a piece I'm missing, though. Were you able to reproduce the same observations with `devel/modstate-monitor`? Any "alt up" SDL events lost in `DFH_SDL_Event()`?

**Comment by myk002** [comment]
Yes, confirmed with `devel/modstate-monitor`:
```
alt=0 ctrl=0 shift=0  <-- start state
alt=1 ctrl=0 shift=0  <-- tap alt
alt=0 ctrl=0 shift=0  <-- release alt
alt=1 ctrl=0 shift=0  <-- depress alt to alt tab away
```

and there is no next entry when I release `alt-tab`. There is also no new entry when I `alt-tab` back into DF. This matches what I expect given the behavior I'm seeing.

I haven't instrumented `DFH_SDL_Event()` yet but I'll do that next.

**Comment by myk002** [comment]
the keyup event *does* get to `DFH_SDL_Event()`. I added the following line at 2484 (right after `auto ke = (SDL::KeyboardEvent *)ev;`):
```
std::cout << "ev->type=" << static_cast<int>(ev->type) << "; ke->ksym.sym=" << ke->ksym.sym << std::endl;
```

and tailed `stdout.log` in a background process. here is the output overlaid with `devel/modstate-monitor` output:

```
$ tail -F stdout.log &
$ ./dfhack
...
[DFHack]# devel/modstate-monitor start
shift=0 ctrl=0 alt=0 
ev->type=2; ke->ksym.sym=308
shift=0 ctrl=0 alt=1 
ev->type=3; ke->ksym.sym=300
```

type 2 is KEYDOWN, type 3 is KEYUP. 
sym 308 is left alt. 300 is... K_NUMLOCK?  ooooook so what's happening there?

just tapping alt gets sym==308 for both KEYDOWN and KEYUP, but alt-tab consistently sends 300 as the KEYUP sym.

Same for right alt. tapping shows sym==307 for both KEYUP and KEYDOWN, r-alt plus tab sends 300 on KEYUP.

googling for alt-tab and numlock doesn't show anything useful. Can I assume that alt-tab shows 308 for you on KEYUP and not 300?

**Comment by lethosor** [comment]
Interesting! Yep, I see the following when pressing (left) alt+tab:
```
ev->type=2; ke->ksym.sym=308
ev->type=3; ke->ksym.sym=308
```
FYI, sometimes I use `Core::print()` for debugging, although it's printf-style instead of C++-style I/O.

I also didn't find any obvious SDL-related discussions on the matter, but I did run into this as a possible solution: https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/blob/57a423e0b2124f578529e2ba5f70ef26d463b769/neo/sys/sdl/sdl_events.cpp#L890

I think this likely wouldn't cause any regressions because DFHack already doesn't handle cases where modifiers are held down when the DF window gains focus - if I hold Ctrl, Alt, or Shift, then click into the DF window, I _only_ see a key-up event when I eventually release the key, never a key-down event or any modstate-monitor output. Basically, if we don't handle already-pressed modifiers when the window gains focus, we can just set our internal modstate to 0 on focus.

**Comment by myk002** [comment]
That looks promising, though I note that it's in a `#if SDL_VERSION_ATLEAST(2` block. We're on 1.2, aren't we?

**Comment by myk002** [comment]
Ah, scrolling down a bit in that file, I see there is a SDL 1.2 version of the handler below:
https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/blob/57a423e0b2124f578529e2ba5f70ef26d463b769/neo/sys/sdl/sdl_events.cpp#L955

**Comment by myk002** [comment]
after the proposed fix, test output looks like this:
```
# devel/modstate-monitor start
alt=0 shift=0 ctrl=0 
ev->type=2; ke->ksym.sym=308   <-- alt down
alt=1 shift=0 ctrl=0 
ev->type=3; ke->ksym.sym=300   <-- tab down, release tab, release alt
alt=0 shift=0 ctrl=0                   <-- alt tab back into DF (no instrumented output)
```
