### ISSUE TITLE
How do you check if a tree is done growing?

### ISSUE THREAD

**Issue by aljohnston112** [DFHack/dfhack#1900]
I am trying to see when a tree is done growing, but got it wrong. Pretty much all trees pass this check.

```
                    if (plantRaw->max_trunk_height*plantRaw->max_trunk_diameter*plantRaw->max_trunk_diameter <= trunks) {
                        doneGrowing.push_back(plant);
                    }
```

**Comment by PatrikLundell** [comment]
If a tree allows for trunk branching you can get trunk tiles on tiles outside of the main trunk. Also, since almost all trees have a max trunk diameter of 1, the check boils down to the number of trunks found (which I assume the variable contains) at least matching the max tree height, which is frequently satisfied for trunk branching trees well before those reach their maximum height.

I don't know what criteria DF uses to determine a tree has finished growing. It might be an unidentified flag, or DF may just keep performing growth checks periodically and have those fail to change the tree. Also note that the trunk(s) may finish developing before all the smaller branches have reached their maximum extent, and that trees can be blocked from developing further due to obstacles (both sideways and vertically in the form of buildings, terrain, and other trees). Being blocked vertically is particularly common among cavern trees.

**Comment by lethosor** [comment]
Was this addressed on the [forums](http://www.bay12forums.com/smf/index.php?topic=164123.msg8293981#msg8293981)?

**Comment by myk002** [comment]
closing old issues
