### ISSUE TITLE
Buffered input is lost when Core::getInstance().setHotkeyCmd() is called

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1970]
I'm not sure if there's anything we can do about this, but I wanted to check my assumptions before I made changes to work around the issue.

I was looking at #1908 and I saw @TymurGubayev's `feed_key()`-based script to configure `autogems` to not cut rock crystal. I thought I'd give an example for how to do this in `quickfort`, which would be easier to read:
```
#query toggle rock crystal in autogems
^oWGr&^^^q
```
When I tested my example, though, I found that it didn't work. Quickfort would get to the `autogems` config screen, but got stuck there. After investigating, I found that pressing `G` on the standing orders -> workshop orders screen causes `autogems.cpp` to call `Core::getInstance().setHotkeyCmd("gui/autogems");`. I remembered from my earlier usage of `setHotkeyCmd()` that it queues up a command to be run on the next frame. I believe this is causing the rest of the input that `quickfort` is sending to be processed before the `gui/autogems` gui gains focus.

Is it possible to stop handling input when `setHotkeyCmd()` is called and defer further processing until the "hotkey command" has been executed? Is this behavior desirable -- that is, it solves my use case, but does it harm others?

If deferring input processing is not feasible, a potential workaround is to pass the complexity on to the blueprint author. I could implement the `{Wait}` query blueprint alias by calling `script.sleep(1)` and requiring the blueprint authors to add `{Wait}`s where necessary. This should not be a common case, but it will be a wart. This would also require me to move at least the blueprint running portion of quickfort into "async space" via `script.start()`, which may involve interesting challenges.

**Comment by lethosor** [comment]
The problem is essentially that `setHotkeyCmd()` is asynchronous - it schedules the command to be run on the next OnUpdate call. In most DF cases, when `feed()` creates a new screen, the new screen is on top of the stack by the time `feed()` returns. In this case, however, the autogems screen isn't created until after DFHack yields control back to DF.

For example, running this from the main fortress mode screen creates a new screen immediately:
```
[lua]# scr:feed_key(df.interface_key.D_UNITLIST) print(dfhack.gui.getCurViewscreen())
<viewscreen_unitlistst: 0x7fffbc0965f0>
```

but running this from the o-W screen doesn't until later:

```
[lua]# scr:feed_key(df.interface_key.CUSTOM_SHIFT_G) print(dfhack.gui.getCurViewscreen())
<viewscreen_dwarfmodest: 0x7fffb2101c70>
```



> Is it possible to stop handling input when `setHotkeyCmd()` is called and defer further processing until the "hotkey command" has been executed? Is this behavior desirable -- that is, it solves my use case, but does it harm others?

I would say that it's not something we should do, because the point of `setHotkeyCmd()` is to not block DF. It's intended for running commands through the `keybinding` command, which should run _pretty_ soon after a user presses a key combination, but the exact timing doesn't matter.

There might be a safer way to run Lua code from within a `feed()` method, though. I went with `setHotkeyCmd()` instead of `Core::runCommand()` based on past experience with deadlocks. I suspect that `runCommand()` _might_ cause a deadlock if called from `feed()`, particularly if the command tries to acquire a CoreSuspender (which it would in this case, since `gui/autogems` is a Lua script), but it also might not. I would have to actually test on my end to determine if there's a safe option that does allow us to create Lua screens synchronously from `feed()`.

**Comment by myk002** [comment]
No need to dig too deeply. I might poke at it a little, but I'm not strongly opposed to the workaround I proposed. Making quickfort asynchronous would give me the opportunity to explore other interesting features anyway.
