### ISSUE TITLE
Autofarm only planting "discovered" plants

### ISSUE THREAD

**Issue by Vettlingr** [DFHack/dfhack#1988]
Autofarm have had its ups and downs and has been unreliable at times.

Latest issue is that autofarm fail to retcognize plants and/or seeds bought from human caravans.

To recreate this issue in DF
Embark close to humans
Either wait or -force human caravan
Buy or seize all the seeds
Observe how Autofarm will only recognize some or all seeds bought
May take a few tries before substantial results

Alternate easier way to recreate issue in DF:
Embark or open a save, enable Autofarm
Use -create-item to create SEEDS your fortress or civilization do not have access to
Observe how they will not be recognized by Autofarm (i.e. added to the autofarm status list)

Fix seems to be removing the condition that autofarm only indexes plants and seeds that are "discovered" by your civ or local civ.

Issue seems to have been solved late october, but changes still need to be commited

**Comment by ab9rf** [comment]
I remember the discussion and validation on this issue. `autofarm` only considers plants that have been "discovered" by the fortress entity, and seeds bought from a caravan (or spawned using `create-item`) are not considered "discovered".

Since the core game allows planting "undiscovered" seeds, there is no reason for this limitation. I have no idea why this limitation (which was in the original Ruby `autofarm` I wrote in 2012) is there, and thus it should be removed.

**Comment by myk002** [comment]
This just requires the removal of this line, right?
https://github.com/DFHack/dfhack/blob/3d8da260322358679dc2f26c6b662f9d081d5464/plugins/autofarm.cpp#L191

**Comment by ab9rf** [comment]
> Fixing this bug just requires the removal of this line, right?
> 
> https://github.com/DFHack/dfhack/blob/3d8da260322358679dc2f26c6b662f9d081d5464/plugins/autofarm.cpp#L191

It would be better to remove the enclosing braces as well and reindent.

**Comment by myk002** [comment]
Do you want to spin the PR, or should I?
