### ISSUE TITLE
warn about invalid values in config files

### ISSUE THREAD

**Issue by Moth-Tolias** [DFHack/dfhack#2029]
as per this post on the forums: http://www.bay12forums.com/smf/index.php?topic=179650.0

**Comment by myk002** [comment]
Can DFHack detect invalid settings? I guess it's possible to write a verifier based on documentation in the init files, but toady could change things any time.

Perhaps it would be more appropriate to report this on the df issue tracker: https://www.bay12games.com/dwarves/mantisbt/my_view_page.php

I think it should really be df that prints a warning whenever a config value is unrecognized.

**Comment by quietust** [comment]
In order to do this, DFHack would effectively have to **duplicate** the game's own config parsing code, and I'm not sure it's worth our time to do that - it would be much more effective to simply get Toady to fix the problem himself.

For what it's worth, the above-linked config check only looks for the values "YEARLY" and "SEASONAL" and assumes that any other value means "nothing".

**Comment by myk002** [comment]
Closing out of scope bugs
