### ISSUE TITLE
Make script execution logging verbosity configurable

### ISSUE THREAD

**Issue by Rumrusher** [DFHack/dfhack#2045]
So was wondering if Script logging could be optional so that it doesn't end up mass printing logs the in a game session mostly with OnMapLoad, SC_WORLD_LOADED and any onLoad stuff as for folks who constantly shuffle between saves or save scum this would start to get annoying quick on a causal playthrough, otherwise it's seems like neat option for debugging.

**Comment by myk002** [comment]
Idea I had for this. We have a configurable logging framework already set up for exactly this kind of use case. We could:

1) convert the script logging to use the logging framework instead of directly printing to the console
2) maybe modify the output format of the logging framework to be a little less technical. we'll see. I'm thinking we don't need milliseconds, at least.

in this case, the plugin could be "core", the category could be "script" and the message level could be INFO (naming is hard. final identifiers pending discussion), so those who do not want to see these messages could add the following line to their `dfhack.init` files:

```
debugfilter set warning core script
```

which would filter out anything at info or below
