### ISSUE TITLE
command-prompt doesn't wrap command output

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2079]
If the command you run happens to output long lines, they will run off the right side of the screen and are unable to be read.

We should implement output text wrapping in the plugin here: https://github.com/DFHack/dfhack/blob/develop/plugins/command-prompt.cpp#L137

**Comment by myk002** [comment]
There is an implementation of `wrap()` in dfhack.lua that can be called directly or ported to c++.
https://github.com/DFHack/dfhack/blob/develop/library/lua/dfhack.lua#L431

I don't think we have any scripts that produce huge amounts of output, so performance is unlikely to be an issue. Therefore I suggest marshalling the string to Lua, wrapping the text there, and marshalling it back. That way the wrapping behavior is sure to match. See the buildingplan plugin for how it sends strings to Lua and retrieves them from the Lua stack after the call.

**Comment by lethosor** [comment]
We also have a wrap implementation in C++: https://github.com/DFHack/dfhack/blob/bf60879c8152d1869a6635c1725e17ea6d25a84b/library/MiscUtils.cpp#L171

I'd generally prefer to have the implementation be done in C++ if we decide we need a single implementation. This one is a bit tricky to wrap because it returns a container, and I don't believe we have the ability to automatically convert a std::vector to a Lua table in our wrapper layer.

**Comment by myk002** [comment]
If we already have an implementation in c++, then yes, let's definitely use that. I just didn't want a *new* implementation of word wrapping just for this bug

**Comment by softmoth** [comment]
I've started looking at this. Should have something soon, feel free to ping me if needed.
