### ISSUE TITLE
add in-game help info to labormanager

### ISSUE THREAD

**Issue by qeveren** [DFHack/dfhack#2112]
Just for convenience and keeping in line with other plugins and scripts, "labormanager -help" (or similar) should produce at least an outline of the advanced features detailed in the manual.

**Comment by myk002** [comment]
@ab9rf what are your plans around labormanager (and its siblings)? Can you include this in your work?

**Comment by ab9rf** [comment]
I'm still fairly inchoate about specific plans at this point, in large part because The Toady One has fairly clearly indicated that the next release will have a completely different labor system and so I'd be burning a lot of effort on something that probably won't survive the next DF release.

At the moment, I'm probably going to limit myself to efforts to eliminate the code duplication among `autolabor`, `autohauler`, and `labormanager`, and reserve any effort to improve how labormanager works until after either we see what the next DF release offers, or it becomes apparent that the next release is not as imminent as previously anticipated. However, expanding the in-tool help text somewhat is not an unreasonable target.

The other issue is going to be finding time to do any of all this.

**Comment by myk002** [comment]
as of DFHack 0.47.05-r7, labormanager help text is how available in-game via `gui/launcher` and `help`
