### ISSUE TITLE
Make tree holes not holes again

### ISSUE THREAD

**Issue by cppcooper** [DFHack/dfhack#2167]
Wouldn't it be nice if we could cut trees directly over dug out rooms without creating a dozen entry points for invaders? Yea I think that'd be nice too. One of us should fix this bug that is actually just a feature.

My initial thought is to detect a hole where once was a tree, and fill it in with dirt so it isn't a hole.

**Comment by Bumber64** [comment]
How do you determine if a tree used to be somewhere?

You could probably monitor tree chopping jobs and handle it right then. (Since the tree info is deleted when it completes, you probably need to intercept before the job is completed, save the tree location, then fix the location after the job completes.) However, I'm not sure what you'd do about fires (assuming those destroy trunks) and ballista bolts.

I think Toady said he fixed the bug for the next release, so it might just be worth waiting on that, instead.

**Comment by cppcooper** [comment]
I was lead to believe the exact opposite. It does seem though that it is getting fixed, so I'll just go ahead and close this.

Otherwise I think checking a job might just be the most efficient way. Scanning the top soil for trees every so often to maintain a map of where the trees are.. or designated trees... might be a good alternative.
