### ISSUE TITLE
Get the Persistence module working with the new save layout

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2570]
including timelines

**Comment by ab9rf** [comment]
going to mention here that i'm not certain that the code to determine the location of the save folder (for loading) is working correctly, especially with respect to timeline saves. in testing i've had problems with it appearing to read persistent data from the wrong place or otherwise doing weird things i cannot yet explain

**Comment by myk002** [comment]
should we close this issue since the wonkiness with timeline saves is a vanilla bug?

**Comment by ab9rf** [comment]
we may need to revisit it once bay12 addresses the underlying issue (since they might fix it in a way that breaks our code) but we probably don't need to keep this open until that happens

**Comment by myk002** [comment]
ack, closing then. I have a note to check for other uses of data/save, but that will be separate from this issue.
