### ISSUE TITLE
Quickfort digs and places constructions, does not create stockpiles or minecart rails

### ISSUE THREAD

**Issue by themaster567** [DFHack/dfhack#2645]
Tested by running the /industry2 command for the dreamfort pack after previously using the /dig_all command. It creates the workshops, doors (didn't have any made yet so they were cancelled), and minecart stoppers, but no rails for minecarts or stockpiles. 

![image](https://user-images.githubusercontent.com/8242023/213241787-4d799f17-d8c3-4798-92d2-2a4c7851d8e5.png)

EDIT:
Upon further testing, this issue definitely extends to everything. It is incapable of making stockpiles or anything outside the scope of designations for digging, workshops constructions, some furniture. It is also unable to set work orders, as it spits out such a flood of errors that I can't even select all of it to paste.

**Comment by myk002** [comment]
This is correct. `place`, `zone`, `query`, and `config` modes have been entirely disabled until they can be reimplemented for steam DF.

Note that minecart rails should work, but are not built in this blueprint. quantum stockpiles don't require them. only a track stop is needed. Dreamfort doesn't build any minecart rails (though as an aside, I've been toying with a design for a minecart-driven quarry level. it's hard to justify, though, since wheelbarrows are already so efficient)

**Comment by themaster567** [comment]
Good to know! I'll close this then since it isn't a bug, just something that will gradually come online as the alpha progresses.
