### ISSUE TITLE
DFHack 50.05-Alpha1 Quicksave not working reliably

### ISSUE THREAD

**Issue by JezaGaia** [DFHack/dfhack#2663]
I've been testing quicksave by always using the command before saving by quiting to title menu and comparing the state of both saves. At first it seemed to work well, I had 3 perfect saves, then on the forth the quicksave didn't show at all when entering the "continue active game" screen. I could see the 2 previous seasonal autosaves and the save made on exit (region folder) but not the autosave made by quicksave.
I checked in my DF Save directory and the folder was there, the timestamp of the last updated files inside were coherent with the normal save, almost identical just a bit earlier (seconds).
I had other succesful quicksaves after but many failed ones too.

I have some mods from the workshop so I can't guarantee the issue doesn't come from those but I never had any issue even using the "save and keep playing" feature from premium DF and I did dozens if not more at least with the same mods.

**Comment by lethosor** [comment]
quicksave isn't supposed to make separate autosaves - it's supposed to save over your current save, just like a "save and exit".

**Comment by myk002** [comment]
it looks like it now creates an autosave in the autosave rotation. I'll update the docs. I haven't seen any unreliable behavior, though, so I'll keep this bug open for investigation

**Comment by brnhensley** [comment]
I'm also having a problem with quicksave, as far as I can tell it hasn't made any saves for me.  I used it a lot today because I'm getting a crash. I saved about 3 times since the last seasonal auto-save, but the crash happened again and none of my saves are here since that beginning of the last season.

All of my quicksaves were after "early summer, 101". The Autosaves are for that season and the previous two seasons, and my last "Active save" is from the previous year. So quicksave did not overwrite either type of save. I did load all 4 them all to make sure the metadata wasn't just messed up, but no, none of my quicksaves exist.

![saves](https://i.imgur.com/qRU5I0y.png)

**Comment by lethosor** [comment]
Hm, so maybe it doesn't work if you save often enough in a season?

We're really just setting a flag that DF uses itself to trigger the autosave logic, so a couple possibilities I can think of are:
* DF could have changed its autosave behavior
* There could be multiple flags now, and we could be setting the wrong one
* 
Either one of these would require some more in-depth reverse-engineering to determine.
