### ISSUE TITLE
Dig-now Channel issue

### ISSUE THREAD

**Issue by nutwick** [DFHack/dfhack#2720]
Dig-now seemed to mine instead of channel in this instance. 

![image](https://user-images.githubusercontent.com/68620392/214730543-9a82d8bf-bea4-48ea-8569-b2b93e7435b6.png)
![Recording 2023-01-25 at 16 47 03](https://user-images.githubusercontent.com/68620392/214730563-f66fbdec-d46b-4045-8a19-627e0d9d0057.gif)

**Comment by myk002** [comment]
The issue (as Rose noticed from the screenshot on Discord) appears to be that `dig-now` is channeling out every *alternate* layer. What is likely happening is that after one layer is channeled out, the next layer becomes invalid for channeling due to the lack of rock (because the layer that was just channeled removed it), so that layer is skipped. The logic either needs to be updated to process levels in the opposite direction or otherwise handle this case.

I believe the code goes in the order it does to support successive levels of ramps, so the fixer for this issue should check that both channels and ramps work over multiple levels.

**Comment by cppcooper** [comment]
Oh, I forgot to open an issue about this in December. I totally forgot I encountered this.

I imagine running a check to detect this situation, then re-applying the designations and running the process again could also solve it. Though that does feel like more of a hack than solution.

**Comment by myk002** [comment]
I'm sure it can all be done in a single pass. It just needs a better algorithm than the one I wrote
