### ISSUE TITLE
inception denied: opening gui/launcher from within gui/launcher hangs

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2740]
reported on dfhack discord

**Comment by lethosor** [comment]
The intended behavior is to close the launcher: https://github.com/DFHack/scripts/blob/ff462de7c4394b9a2df008391ac7ec2878d7021f/gui/launcher.lua#L774-L781

@ab9rf reports on Discord that the hang happens here, because `screen == screen->child`: https://github.com/DFHack/dfhack/blob/bf95520949edc67fc6965d026861e6be58d4b167/library/Core.cpp#L1832-L1833

**Comment by lethosor** [comment]
This appears to have been introduced after 0.47.05-r8 - in that version, running gui/launcher from gui/launcher just dismisses the launcher.

**Comment by myk002** [comment]
This probably happens because the current screen is in limbo in the hideGuard while the new instance is instantiated. I wonder if quickcmd is also affected, since it uses the same technique.
