### ISSUE TITLE
DFHack config is not persisted when "Save and continue playing" is used

### ISSUE THREAD

**Issue by TheBloke** [DFHack/dfhack#2798]
I very commonly use the new v50 feature "Save and continue playing" to make backup saves, allowing me to reload to before I do a certain thing, and to make periodic named backup saves.

Unfortunately I've just realised that when I do such a save, none of my DFHack config is saved.  `gui/control-panel` changes are not persisted, `autoclothing` orders are not persisted, `automelt` config is not persisted, etc.

Steps to re-create:
1. Change something that DFHack will persist, such as running `autoclothing leather shoe 1`
2. Menu -> Save and continue playing -> give it a name
3. Menu -> Save and return to title menu -> Save to this timeline
4. Now load both of the saves made in 2 and 3, confirming that the new config is saved OK in step 3, but is not saved in step 2.

I realise that the DFHack intro warns against the new saves (was this one reason why?) But I've been using the "Save and continue playing" saves extensively, and occasionally exclusively, and they've worked totally fine for me in vanilla.  So it'd be really helpful if I could also rely on them for persisting DFHack config.

**Comment by ab9rf** [comment]
Timeline saves are broken in vanilla Dwarf Fortress. Since DFHack leverages Dwarf Fortress's saving mechanics, DFHack persistent data is also broken in timeline saves; this is not a problem we can fix.

We sincerely hope that Bay12 will fix this bug in the future. Until Bay12 fixes this bug, the DFHack team _strongly_ recommend that players refrain from using timeline or manual saves.
