### ISSUE TITLE
Confirm does not disable.

### ISSUE THREAD

**Issue by AndrielChaoti** [DFHack/dfhack#3106]
Title.

Running `disable confirm` does not actually stop the confirmation dialogs from popping up.

Image showing how things are set:
![image](https://user-images.githubusercontent.com/3628387/227816287-3955344b-53f7-475c-8771-38c71c43ed82.png)

**Comment by lethosor** [comment]
Did you disable the plugin while a dialog was still open? Or before the confirmation dialog showed up?

**Comment by AndrielChaoti** [comment]
No, this screenshot is just to show the current settings. That dialog popped up even though confirm was disabled globally.

**Comment by myk002** [comment]
Looking at the code, `disable confirm` sets the enabled flag to false, but doesn't actually change any internal state. for example, it doesn't disable the viewscreen interposing that intercepts the input and spawns the confirmation dialogs.

but fixing this isn't entirely straightforward since we have to consider the enabled setting for the individual confirmation dialogs and state persistence. when you run `disable confirm`, what happens to the state of the individual confirmations? do they show as enabled (as they were when confirm itself was enabled) or do they show disabled to reflect that they aren't currently active? if you then enable one of the dialogs in `gui/confirm`, what happens? Do you re-enable `confirm`? do you save that you want that dialog enabled when `confirm` is enabled, but you don't actually make it active?

**Comment by myk002** [comment]
We've classified `confirm` as a "system service", so I think it should behave like `overlay`. That is, enabled state is distinct for the service and the individual elements.

This means:

- [ ] interposing should be enabled if the service is enabled AND the individual confirmation is enabled
- [ ] `gui/confirm` and the `confirm` status output should show a warning if the service is disabled, but I don't think we need to provide a toggle -- in general the service should not be disabled since it's enabled by default at a system level at startup. the player-usable knobs are the enabled settings for the individual confirmations. the `confirm` service would only be disabled for debugging.

**Comment by AndrielChaoti** [comment]
The state of each option stayed enabled when I ran disable confirm. It's likely just a ux problem if it's intended to work as you stated in a previous comment. (Ps, turned off because of preferences). Andrielle Granger (she/her)On Mar 27, 2023, at 18:57, Myk ***@***.***> wrote:﻿
Looking at the code, disable confirm sets the enabled flag to false, but doesn't actually change any internal state. for example, it doesn't disable the viewscreen interposing that intercepts the input and spawns the confirmation dialogs.
but fixing this isn't entirely straightforward since we have to consider the enabled setting for the individual confirmation dialogs and state persistence. when you run disable confirm, what happens to the state of the individual confirmations? do they show as enabled (as they were when confirm itself was enabled) or do they show disabled to reflect that they aren't currently active? if you then enable one of the dialogs in gui/confirm, what happens? Do you re-enable confirm? do you save that you want that dialog enabled when confirm is enabled, but you don't actually make it active?

**Comment by AndrielChaoti** [comment]
For the UX side of the issue, is that I expeced that `disable confirm` would stop the dialogs from interposing entirely, regardless of specific configuration. I can't say if I'm the only one who expects this.

**Comment by lethosor** [comment]
> Looking at the code, `disable confirm` sets the enabled flag to false, but doesn't actually change any internal state. for example, it doesn't disable the viewscreen interposing that intercepts the input and spawns the confirmation dialogs.

`disable confirm` *used* to disable all of the vmethod hooks: https://github.com/DFHack/dfhack/blob/0.47.05-r8/plugins/confirm.cpp#L555-L571
Compare to: https://github.com/DFHack/dfhack/blob/b9d95c5a0bbc68846952c54ed91959ac55835b1f/plugins/confirm.cpp#L618-L626

This appears to have been changed in #2904 with https://github.com/DFHack/dfhack/commit/b4bd806134910ec4709dc8f836887591b9a6fa46, perhaps inadvertently in an attempt to prevent the inverse behavior of dialogs showing up when the plugin is enabled (@robob27 can you confirm?)
