### ISSUE TITLE
DFHack terminal should auto-hide on Steam Deck

### ISSUE THREAD

**Issue by rattlesnakejones** [DFHack/dfhack#3182]
Wanted to follow up and create this issue as suggested by someone on Reddit. 

When loading into DFHack and Dwarf Fortress on Steam Deck, there files load and I’m given the message DFHack is loaded. Have a nice day! But I cannot move on from here. 

The suggestion given is to go into the text files and add a command to “hide” but the Reddit user also said they might need to put more priority into adding this themselves. 

I’m just creating this issue for visibility per their suggestion. Thank you.

**Comment by myk002** [comment]
Let's see if we can detect Steam Deck and autohide the terminal in that environment.

**Comment by myk002** [comment]
Another idea is to add `hide` to the "System" tab in `gui/control-panel`. Then Steam Deck users can just enable it there without having to edit any config files. The question is, of course, how do they get to `gui/control-panel` if they're stuck on the terminal window..

**Comment by KarlXerri** [comment]
I came here to report this same issue. I’d previously seen the instructions in the docs to add the hide command, but expected in the Steam release for this to be automated as it’s now akin to an integration rather than a custom tool, at least to the typical Steam user.

as per your observations @myk002 , unless you can get to the gui, you won’t be able to disable it in the system menu, it’ll need to be an auto detect, or maybe a boot option in Steam could work? Like when you start a game and get the option to boot into regular or VR mode, maybe the same to choose your device type, with “Steam Deck” or “Other” as the options.

**Comment by myk002** [comment]
we could eventually make this configurable (in case there are Steam Deck) users who *want* the terminal to show), but for now we can probably hard-code this behavior.

I suggest:

- just before we load `dfhack.init`, we do the detection for Steam deck
- if we're in steam deck, call Core::run_command('hide') (or just call its internal implementation -- it's a builtin command anyway)

that way, the player can still override in `dfhack.init` if they want to by adding a `show` command.

The big open question: how do we detect that we're running on Steam Deck?

**Comment by ab9rf** [comment]
https://www.reddit.com/r/SteamDeck/comments/telfda/how_to_detect_if_software_is_running_on_steamdeck/

**Comment by myk002** [comment]
Nice. Thanks for that link. We have a model for proxying a library that may or may not be there in dfhooks. I wasn't really keen on doing this right now, but that seems like a better option than scanning `/sys/devices/virtual/dmi/id/board_vendor` and `/sys/devices/virtual/dmi/id/board_name` (which there is just no way for me to verify the efficacy of in this short time)
