### ISSUE TITLE
Crash while testing the new steam version

### ISSUE THREAD

**Issue by Black616Angel** [DFHack/dfhack#3192]
Okay, I was testing the steam-version of dfhack and the game crashed, while I was manually removing weird looking tomb-zones, where coffins were only planned by dfhack.
I don't know if that correlates.

What else is needed to fin and maybe fix an issue?

I play on Linux on the 21.04 version of Pop-OS.

**Comment by ab9rf** [comment]
this may be a vanilla bug. removing a zone that is assigned to a unit without first unassigning the zone leaves a dangled pointer in the unit to the now-deleted zone. dereferencing this pointer leads to undefined behavior.

tombs assigned to dead units cannot be unassigned. the only known mitigation of this bug is to immediately save and reload after deleting an assigned tomb zone, since the dangled pointer is not used while saving and is not itself persisted in the save.

**Comment by Black616Angel** [comment]
Oh, this checks out. I was transferring old tombs to a new location.
