### ISSUE TITLE
Option to start DF without DFHack

### ISSUE THREAD

**Issue by RNGStrategist** [DFHack/dfhack#3198]
Can you add logic to disable DFHack if a specific parameter is passed?launching DFHack would get you DF with DFHack and launching DF directly would get you vanilla DF. This would allow people to simply add the parameter say to their steam launch options and switch back and forth as desired without messing with the files.

**Comment by myk002** [comment]
If this is in the context of "vanillafying" the UI, would these ideas be useful: https://github.com/DFHack/dfhack/issues/3207#issuecomment-1502498320

**Comment by myk002** [comment]
So I looked into this a bit. The code to disable DFHack is simple (we have a nice shim layer where we can do that), but it is not easy at all to find a way to pass a useful parameter through Steam.

The intended user experience, if I am understanding correctly, is that a player can set things up in Steam so "Playing" DF in the Steam client runs DF without DFHack and "Playing" DFHack in the Steam client runs DF with DFHack.

The two options are:
1. set an environment variable (e.g. DFHACK_DISABLE=1)
2. pass a commandline parameter (e.g. --disable-dfhack)

environment variables are not easy to set in Windows, and even if you do set them on the commandline (e.g. `DFHACK_DISABLE=1 steam steam://rungameid/975370`), the trip through Steam to launch DF loses the environment. 

Steam *does* provide players with a nice easy way to pass parameters to a game:
![image](https://github.com/DFHack/dfhack/assets/977482/9246fdda-f847-417e-ace5-94826a4ca604)

However, if you add that parameter to DF, DFHack will always be disabled since DFHack uses Steam to launch DF!

A player could add or remove the commandline parameter to disable DFHack when desired, but it would not be as easy as selecting one or the other to play in the Steam client.
