### ISSUE TITLE
[Feedback] Steam beta - terminal update

### ISSUE THREAD

**Issue by Mondrogar** [DFHack/dfhack#3207]
Hey, DFHack noob here. Im using exclusively ingame UI so DFHack terminal window feels redundant. Im not sure if terminal has any funcionality that gui does not, but usualy I just hide terminal window.

On my linux machine (Popos) the terminal window came up, minimised dwarf fortress so i had to maximise it(playing df in fullscreen, steam, proton). Can confirm that Hack loads pretty fast.

I dont have my windows machine at hand atm, so cant verify that.

Also I have a question, is there I way how to deactivate dfhack build UI? I love it but there are specific moments when I need old one. Now Im uninstalling dfhack every time I need old UI back.

Build UI as in building workshops, walls and stuff

**Comment by Mondrogar** [comment]
Reddit comment thread:
https://www.reddit.com/r/dwarffortress/comments/12hp9dd/comment/jfq5ojv/?utm_source=share&utm_medium=web2x&context=3

**Comment by Cubittus** [comment]
The build planner can be minimised by clicking on the up/down arrows in the top-right corner.
Or it can be disabled in the DFHack Control Panel (`Ctrl-Shift-E`) -> `Overlays` tab -> `buildingplan.planner` toggle

**Comment by myk002** [comment]
Let me paste in what I wrote in the Reddit thread about buildingplan since it might be useful for the record here:

There are several ways to get the original build UI back that don't involve uninstalling DFHack.

The first is the minimize button on the top right corner of the planner panel (the one that covers the vanilla build widget panel). You can click that if you just want to use the vanilla UI for occasional buildings.

If you want to disable the DFHack buildingplan UI more permanently, open gui/control-panel, go to the Overlays tab, and turn off buildingplan.planner.

If you want to get all of DFHack's overlays out of the way for a more vanilla look overall, you can go to the System tab in gui/control-panel and disable overlay. Note that it will turn itself back on when you restart DF.

DFHack has docs for all its tools [here](https://docs.dfhack.org/en/latest/index.html). Buildingplan specifically has docs [here](https://docs.dfhack.org/en/latest/docs/tools/buildingplan.html#buildingplan). The docs are also available in-game via gui/launcher.


Later, when Mondrogar clarified that this was in the context of vanillafying the UI for video tutorial purposes, I added:

Ok, I think your options are:

If you want to disable the overlays permanently so your UI is pure vanilla all the time, go to gui/control-panel on the Overlays tab and disable everything.

If you just want to temporarily toggle all overlays off while you do videos then get them back aferwards, you can go to gui/control-panel and toggle the overlay service on the System tab. That will disable all overlays, but keep their individual "enabled" states saved for when you re-enable the overlay service later.

Either way, you'll keep access to DFHack tools via backtick (`) that brings up gui/launcher.

**Comment by myk002** [comment]
Fixed in #3249
