### ISSUE TITLE
CRASH: devel/query when running suggestion from assign-attributes

### ISSUE THREAD

**Issue by John-Ender** [DFHack/dfhack#3267]
In the 50.08-beta branch of DF hack running the following command found in the `assign-attributes` documentation causes Dwarf Fortress to crash

 `devel/query --table df --maxdepth 1 --search [ physical_attribute_type mental_attribute_type ]`
 
 Error log produces

`EARLIEST_COMPATIBLE_NUMERIC_VERSION must be less than or equal to NUMERIC_VERSION!`

![DF_Version](https://user-images.githubusercontent.com/4483110/232928149-a903e955-e5dc-4bd4-bd7d-c24b94005a7f.jpg)

![DF_Hack_Console](https://user-images.githubusercontent.com/4483110/232928159-a1834c7e-562f-40c1-bd51-3568ef05c195.jpg)

**Comment by myk002** [comment]
verified. works in 50.07, crashes in 50.08. @ab9rf could you take a look?

**Comment by myk002** [comment]
btw, the `EARLIEST_COMPATIBLE_NUMERIC_VERSION must be less than or equal to NUMERIC_VERSION!` error is produced by one of your DF mods with a misconfigured info.txt and is unlikely to be related to DFHack

**Comment by lethosor** [comment]
Yep. That message is probably in errorlog.txt. DFHack errors go to stderr.log instead.

**Comment by ab9rf** [comment]
It looks like this has something to do with `steam_mod_manager`, which definitely changed in 50.08 and which I glossed at the time because it was not essential to initial testing. Putnam did provide some information on discord.

**Comment by ab9rf** [comment]
the issue i'm running into is that lua `printall(df.global.steam_mod_manager)` causes lua to crash. fundamentally, this is because this structure contains garbage if the steam API has not been initialized, and nothing should attempt to access its contents prior to this happening. we probably need to mark this structure with the tag for "pointers-may-be-invalid" or whatever it is we use to keep printqall from blithely descending into it

**Comment by ab9rf** [comment]
fixed in 2b8b6a62e0d984746c386b519c5882b6e81a09be, build deployed to steam and verified
