### ISSUE TITLE
[Quickfort] Hide dump designation 

### ISSUE THREAD

**Issue by fricy** [DFHack/dfhack#3352]
Dump designations are a useful tool to add to blueprints for cleanup, but it obscures the shape, and makes it hard to find where to continue with the next phase.
For example this is a carving blueprint with or without dump:

![dump_show](https://user-images.githubusercontent.com/5114750/236241468-4456e709-8810-493d-8d45-77db303e36ae.png)

![dump_hide](https://user-images.githubusercontent.com/5114750/236241537-6b525beb-e317-4e9c-9962-cac3966bf167.png)

Hiding them would help with QOL.

**Comment by myk002** [comment]
I'm not sure if this behavior would be expected or not. by hiding dump, we'd be obscuring the affected area of the blueprint.

What *is* easy to do, though, and has precedent, is to make it not an "error" if the tile has no items on it. Then at least the highlight will be the green diamond instead of the red square. Would that be sufficient?

**Comment by myk002** [comment]
I'll call this fixed by DFHack/scripts#708
