### ISSUE TITLE
Please mark "unavailable" tools in the documentation list of tools

### ISSUE THREAD

**Issue by klenze** [DFHack/dfhack#3503]
At the moment, some tools are tagged unavailable, e.g. they do not work with the latest version of dfhack. 

However, these are not filtered out of the list on https://docs.dfhack.org/en/stable/docs/Tools.html .

As far as I know the only way to get all the available tools from the web is clicking on everything and then closing the tabs with tools tagged unavailable. A list of tools which are not tagged so would be helpful for Noobs like me who don't have an overview of all the plugins. 

Also, it might be helpful to denote why a tool is unavailable. For example, I assume that autogems is not supported because the Steam version of DF only has a generic "Cut Gems" command, while petcapRemover might simply not be ported yet or unavailable due to some other constraint?

Thanks for your time,
   Philipp

**Comment by myk002** [comment]
Up until now, the unavailable tools were left presented very similarly to available tools because they could become "available" at any time. You're right that it's finally time to differentiate them a bit more.

I agree that we should move them out of the regular indices. Our documentation generation system won't make this trivial, though. Unless we modify the doc validity checking routines, removing the docs also means removing the tool itself from the DFHack script path, meaning that "unavailable" tools that actually do work or partially work will no longer be runnable by players who know what they're doing.

Here's one plan:

- audit the unavailable tools (181 of them) to see which can be marked as available and which are hard-broken.
- move the remaining unavailable tools and docs for those tools to an out of the way place in the tree where the existing systems will ignore them.
- manually create a doc page that lists the unavailable tools and their short descriptions, linking to their doc page in an earlier version of the online docs

Another approach could be to modify the doc index generation code to not add the unavailable tools to the indices. That would leave the docs accessible to gui/launcher and the tools accessible to the players. I'm not sure how hard this would be to pull off.
