### ISSUE TITLE
Incorrect thoughts/memories

### ISSUE THREAD

**Issue by AqueM** [DFHack/dfhack#3544]
All fort dwarves, be it the initial 7 or new migrants, experience soapy baths even when there's no soap available, and are miserable due to those baths, when a soapy bath should be a positive thought.
![image](https://github.com/DFHack/dfhack/assets/26459425/aa9f9980-a3f9-468d-bf57-91846245da0c)
Tested without any other mods and after re-installing DFHack - on complete vanilla, this issue doesn't happen.
Used release 50.09 Steam of Dwarf Fortress and DFHack 50.05-r1

**Comment by quietust** [comment]
Are you using the `misery` plugin? One of the specific things it does is create an Emotion with type "MISERY" associated with the thought "SoapyBath".

**Comment by lethosor** [comment]
The docs actually _used_ to be correct, but were changed to match the (incorrect) plugin help message in https://github.com/DFHack/dfhack/commit/756900393f35a415af124da075e9cf2e2221a783 (@myk002 FYI)

@AqueM if you aren't sure if you're using the `misery` plugin, check the output of `plug misery`.

I'm not sure if the changes in https://github.com/DFHack/dfhack/pull/2852 could cause the plugin to inadvertently enable. Prior to v50, the plugin hadn't changed meaningfully since 2016.

**Comment by myk002** [comment]
`misery` is an option in the DFHack control panel, so if it's enabled, it was probably enabled from there

**Comment by AqueM** [comment]
Re-installed DFHack and indeed misery was enabled in the autostart. Thank you for the quick reaction and explanations.

**Comment by lethosor** [comment]
Hm, misery should not be enabled by default, but it's possible that it had been enabled inadvertently and that the configuration persisted across a DFHack reinstall. If you want to completely reset DFHack, you could delete the `dfhack-config` folder before uninstalling (or after reinstalling). That will wipe all of your DFHack settings, though, so I wouldn't recommend this if you're happy with the setup you have now.
