### ISSUE TITLE
location of the data related to the tutorial guidelines been found

### ISSUE THREAD

**Issue by Rumrusher** [DFHack/dfhack#3606]
df.global.plotinfo.anon_1 and df.global.plotinfo.anon_2 affect the tutorial popup and the help guide list showing if you seen a pop up.

anon_1 holds the list that tells the game to never show this tutorial prompt ever again
anon_2 is the tutorial prompt list that shows that you seen the prompt before 
writing a script that remembers the data in these lists and re-adds them back in when the player boots up fort mode again could solve this issue for good, or at least it's doable to write a script that just fills these two lists and never see a help prompt pop up again.

**Comment by myk002** [comment]
notes:
vectors are cleared when you actually embark
IDs:
2: initial embark "do you want the tutorial
13: burrows
14: hauling routes
15: stocks
16: work details
17: nobles
18: justice
21: work orders

nevermind -- this is just df.help_context_type

so we can't safely clear the initial embark message (since there's important logic attached to that), but we can pre-populate the vectors for the popups.
