### ISSUE TITLE
mark set-orientation as available

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3661]
looks like it should work without modification

**Comment by Adda0** [comment]
While this is being worked on, I think the script should be modified to abort with a warning (error) message to the console when the unit ID passed with `--unit` parameter is not found instead of trying to modify the currently selected dwarf. If the player explicitly passed a specific ID, they expect to either succeed with that ID, or change nothing. Not unintentionally modify the orientation of some poor dwarf, whose only offence is that they are currently selected. The modification should be easy and there should be no need to worry about breaking the script, in my opinion.
