### ISSUE TITLE
Realign tooltip ids for `confirm`

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3773]
They've changed and need retuning

**Comment by lethosor** [comment]
Maybe this should use an enum?

**Comment by myk002** [comment]
that would be ideal, but how would we maintain it? there are hundreds of values and no easy header file reference.

or should we just have an enum with mostly nameless values except for the few that we care about? then at least we can realign in structures instead of code?

**Comment by myk002** [comment]
short-term fixed in https://github.com/DFHack/dfhack/commit/b6c4eb77010fe956812710cbb70d44ba12410cb7 but I'll keep this open for more discussion on potentially creating a proper enum

**Comment by lethosor** [comment]
If there are hundreds of values we don't need, we can use a "sparse enum" to skip the ones we don't care about, like `lever_target_type`

Keeping it in sync is a challenge, I agree, but it would reduce the number of clients that need to be updated.

Did you check all of the IDs in b6c4eb77010fe956812710cbb70d44ba12410cb7 or just the ones you updated?

**Comment by ab9rf** [comment]
as a note, you can get the hover text associated with any hover index from `gamest.main_interface.hover_instructions[i]` where `i` is the index of interest. this static array of string vectors is loaded with all of the tooltip texts during game launch (prior to main, so it's a global static constructor).

in theory you could find the hover value by searching the instructions vector for the tooltip text you want, but this is a bit tricky because the elements are string vectors and several tooltips are very similar in their text, and so i wouldn't recommend it at runtime.

**Comment by myk002** [comment]
> Did you check all of the IDs in [b6c4eb7](https://github.com/DFHack/dfhack/commit/b6c4eb77010fe956812710cbb70d44ba12410cb7) or just the ones you updated?

I checked all the IDs that `confirm` uses. The others were still correct.
