### ISSUE TITLE
There are several issues with the startdwarf script.

### ISSUE THREAD

**Issue by BeerNTacos** [DFHack/dfhack#3789]
Per an interview with Blind, Putnam stated she made some updates to startdwarf.

There's a few issues that still exist with the script. Some are just issues that need to be included in documentation, while others may be improved.

- startdwarf is still limited to dwarves numbering seven or higher for the end user. Putnam has stated issues regarding using less than seven dwarves have been addressed. 
- Using startdwarf to create more than 16 dwarves on embark causes issues in which all dwarves are unable to be selected in the "Your Citizens" screen. It is possible to select dwarves near the lower section of the list of dwarves that will cause the selection of dwarves to "scroll" down, but dwarves near the top of the list cannot be reselected to modify skills. It is still possible to make sure all dwarves have selected skills if a saved embark profile has enough skill entries to cover the number of summoned dwarves.

**Comment by ab9rf** [comment]
we can change the bounds in the script to allow 1 to 32767 (which appears to be the limit, although values above 127 will require a structures change) instead of the current 7 or greater

issues with the "prepare" screen are entirely vanilla DF. mitigating them is nontrivial. it might be an idea to have the script issue a caution message if the user selects a number greater than 16. also i suspect the number 16 may be dependent on display resolution
