### ISSUE TITLE
Possible "fix" script for corrupted jobs

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#3861]
Putnam identified the cause of a crash on [KF Discord](https://discord.com/channels/329272032778780672/1049402643342168114/1161111258473439264) where units apparently have references to jobs with an ID of `-1` after loading a save. Unsure how the issue manifests itself before saving, or what the root cause is. In the absence of a fix on the DF side, this snippet can remove references to this type of broken job, and fixed the crash for the original reporter:
```lua
for k, v in ipairs(df.global.world.units.all) do
    if v.job.current_job and v.job.current_job.id == -1 then 
        v.job.current_job = nil
    end 
end
```

The global list of jobs may also need to be cleaned, which this snippet doesn't handle.

**Comment by BranislavSetlak** [comment]
Hi!
Could I get this issue assigned to me? I am a first time open source contributor and it looks rather simple.

**Comment by dhthwy** [comment]
> Hi! Could I get this issue assigned to me? I am a first time open source contributor and this issue looks rather simple.

This one looks simple if it can be done in Lua. Just work on it, submit a pull request, and we will try to help you.

**Comment by BranislavSetlak** [comment]
Thanks, I will try to do as much as I can and if I am stuck I will come here to ask questions. I dont know how many people are affected by this bug but it sounds like it would be good to be solved fast.

**Comment by myk002** [comment]
The best place for discussion and help is the DFHack discord -- https://dfhack.org/discord. You'll probably get faster responses to your questions there.

A good model to follow is https://github.com/DFHack/scripts/blob/master/fix/general-strike.lua, and you can integrate with the control panel by adding the fix script here: https://github.com/DFHack/scripts/blob/master/gui/control-panel.lua#L128

You'll also need help text, similar to this file: https://github.com/DFHack/scripts/blob/master/docs/fix/general-strike.rst

**Comment by ab9rf** [comment]
i'm going to recommend that the fix script assign jobs with a job ID of -1 the next job ID (incrementing it after doing so). we don't know if these jobs can be safely deleted or even if they should be deleted

i'd also suggest validating that the job pointer in each unit is actually a pointer to a job on the global job list. if the unit job pointer points to something that _isn't_ on the global job list, it's probably pointing to a deleted job object, and manipulating that object in _any_ way may cause heap corruption. in this case, it's probably best to clear the unit's current job pointer and do _nothing_ with the job itself because it probably doesn't actually exist

i strongly suspect this is related to the "two dwarfs one job" bug in 50.09 that was causing certain forts to crash with a heap corruption exception on fortress unload. putnam did something to mitigate this in 50.10 or 50.11 (not sure which) but it's possible either that the mitigation introduced a different problem, or that the observed problem is a consequence of past save file corruption from saves that were played in 50.09 

i have a 50.09 save somewhere (sent to me by someone else) that exhibits the doublefree on unload bug. i think it's [this dffd file](https://dffd.bay12games.com/file.php?id=16839) [mods](https://dffd.bay12games.com/file.php?id=16840). might be worth loading this into 50.11 and see if it shows the -1 job id issue
