### ISSUE TITLE
Modify dfhack core to simulate item get capacity for containers

### ISSUE THREAD

**Issue by silverflyone** [DFHack/dfhack#3898]
Refer to conversation thread: https://discord.com/channels/793331351645323264/793331351645323267/1163476020091961364

Modify DFHack::Items::getCapacity

Simulate the item getCapacity logic in dfhack core.

```c
int32_t itemst::getCapacity(itemst *param_1)7

{
  item_type iVar1;
  
  iVar1 = (*param_1->_vtable->getType)(param_1);
  if (true) {
    switch(iVar1) {
    case FLASK:
    case GOBLET:
      return 0xb4;
    case CAGE:
    case BARREL:
    case COFFIN:
    case BOX:
    case BAG:
    case BIN:
    case ARMORSTAND:
    case WEAPONRACK:
    case CABINET:
      return 6000;
    case BUCKET:
      return 600;
    case ANIMALTRAP:
    case BACKPACK:
      return 3000;
    case QUIVER:
      return 0x4b0;
    case TOOL:
      if (*(longlong *)&param_1[1].colddam_point != 0) {
        return *(int32_t *)(*(longlong *)&param_1[1].colddam_point + 0x150);
      }
    }
  }
  return 0;
}
```
This could be used for combine, to ensure container capacities are adhered to.

It's preferred to have it in dfhack core than lua, so if we ever get the export, then it can be swapped out.

**Comment by silverflyone** [comment]
@ab9rf as requested

**Comment by ab9rf** [comment]
reverse engineering note: this function should exactly simulate the DF code at `0x140953150` in v50.11-steam (labeled in ghidra as `itemst::getCapacity` although that name is ours rather than bay12's)

part of the reason for putting this in dfhack core is so that if we ever get this as an export from bay12, we can replace it in dfhack core instead of having to hunt it down in lua -- and also because our current methodology for calling a bay12 exported function cannot be used directly from lua
