### ISSUE TITLE
gui/design overcounts dug tiles for lines

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3927]
it double counts lines

because internally it actually draws lines in both directions?

**Comment by jfisher446** [comment]
The mentioned defect is specifically present in both the Line shape and the Polygon shape tools. The other drawing tools appear to be counting to-dig tiles accurately

The miscount is double the correct value with a line width of 1. (5 long * 1 * 1 = 5 but displays as 10 tiles)
The miscount gets worse when the line width is changed to 2. (5 long * 1 * 2 = 10 but displays as 32 tiles)

**Comment by jfisher446** [comment]
Yes, the miscount is due to how it does actually draw the line in both directions. Each time this plot method is called, num_tiles is incremented. 
https://github.com/DFHack/scripts/blob/0cc4640ef4f73552546db93858fc6d8b854bbda7/internal/design/shapes.lua#L560-L565
On the second call, either _some_, _all_, or _none_ or the tiles should be added, but it's currently counting _all_ in every case.

**Comment by myk002** [comment]
so presumably we'd have to track which tiles have already been selected and just increment the counter for newly selected tiles
