### ISSUE TITLE
Inhibit "error" message: Class not in symbols.xml: 'dfhack_lua_viewscreen@DFHack'

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4101]
this confuses players who think that it indicates a problem. we could maybe filter dfhack viewscreens out where the error message is being printed?

**Comment by lethosor** [comment]
It's not an error message, and it has been reworded multiple times to make it clearer that it isn't an error. I don't really know how we can make it clearer. Maybe somewhere other than stderr.log, but it is really helpful to have these logged sometimes because they can be related to errors, especially during development for new DF versions.

**Comment by quietust** [comment]
I pointed out in Discord that this message should probably **not** be logged for any classes inside the DFHack namespace (which will require separate logic on Windows versus Linux).

**Comment by lethosor** [comment]
Also my favorite suggestion from Discord was prefixing this line with `INFO:`.

Unfortunately with GCC mangling and our current implementation of `doReadClassName()`, the leading `DFH` in `DFHack` gets stripped out:
https://github.com/DFHack/dfhack/blob/bbc79d70c04a993d84da591e8cd0bf18bab15075/library/Process-linux.cpp#L120
