### ISSUE TITLE
Persistent data should be stored differently

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#414]
There is a notable overhead per historical figure. Histfigs are the simplest way to do persistent data but if instead we carefully update a dfhack-specific file every time the game saves then we can dramatically reduce this overhead and possibly even decrease latency on persistent data lookups.

**Comment by Putnam3145** [comment]
It's been a couple months since this was posted in, but I'm very, very against file-saving; the memory overhead is *extremely* worth not having to read files. Roses' class system using persist-table already causes 300 ms stutters every time it checks a unit's experience in Fortbent with the current system--if it were to check the hard drive, that number could be significantly higher.

On the other hand, I doubt anyone will ever get to as extreme a use case as me.

**Comment by expwnent** [comment]
It's a lot slower in Lua than in C++ and this would be on the C++ side. Furthermore, Roses' system requires a lot of parsing of text, which is probably the slowest part, not the file I/O.

**Comment by Putnam3145** [comment]
I'm saying that it's slow even without file i/o, which could be far slower.

**Comment by expwnent** [comment]
Neither system uses file I/O on queries. That's only done when the game saves. I'm surprised it's that slow in the current system just for queries. That should definitely improve with the new system because it will have to just traverse a few pointers instead of doing a few iterative binary searches through historical figures.

**Comment by lethosor** [comment]
We talked about holding off on the huge JSON rewrite stuff until after r1 on IRC (if I'm remembering that correctly).

**Comment by expwnent** [comment]
Yes.

**Comment by BenLubar** [comment]
Fixed as of 0.44.12-r3
