### ISSUE TITLE
When digging down stairs on the surface `dig-now` will sometimes create underworld gates.

### ISSUE THREAD

**Issue by MagistrumT-T** [DFHack/dfhack#4226]
I have no idea what implications this has.

**Comment by myk002** [comment]
I'm interested in discovering *why* it's creating underworld gates. Is there an enum value set incorrectly?

**Comment by MagistrumT-T** [comment]
Upon further inspection it only opens gates to the underworld when digging tiles where there is a plant shrub or sapling. The downstairs are completely usable for dwarves, they just happen to be made of the material 25 Underworld Gate, which is cool. I thought they had some special property from being only seen in underworld spires.

Now that I interpret it as only missing the material, just throwing this out before looking, could this have any relation to #3286 ?

**Comment by myk002** [comment]
> could this have any relation to #3286 ?

it could, yeah, and I still don't really understand why that's happening either

**Comment by quietust** [comment]
Shrubs and Saplings have a `tiletype_material` of `PLANT`, and since there are no valid stair tiles with that material it's presumably picking whatever's available and somehow getting the ones with a material of `UNDERWORLD_GATE`.

The easiest solution would probably be to add a special case for that material and replace it with `SOIL`.
