### ISSUE TITLE
[Bug] Suspendmanager doesn't suspend jobs which block a second job that some third job allows dwarves to reach

### ISSUE THREAD

**Issue by gondor2222** [DFHack/dfhack#4466]
![stairs1](https://github.com/DFHack/dfhack/assets/17519588/ac6cb5fa-66b7-46a1-9ea8-3ba327f30985)
![stairs2](https://github.com/DFHack/dfhack/assets/17519588/487d374a-4324-4967-94fc-73744b273e26)

I was building a pretty simple staircase with side and corner walls, and even with suspendmanager my dwarves built a side wall that blocked a corner wall (second image), because at the time the side wall was reachable but the corner wall was not (because the side wall below this floor was not yet built, layout of completed lower floor shown in first image)

**Comment by gondor2222** [comment]
The inverse issue sometimes also occurs but is difficult to trigger reliably: when trying to build an elevated wall from scratch from both ends, no single job will block any other job (because building a single block still allows dwarves to extend the wall from both ends), but sometimes a second dwarf will complete a second wall piece before suspendmanager can update, leading to a stretch of unreachable wall pieces

**Comment by chdoc** [comment]
Okay, if I understand correctly, the issue is as follows:
1. `riskBlocking` has a check `if (!isSuitableAccess(pos)) return false;`
2. `isSuitableAccess` basically checks `walkable` (i.e., non-zero walkablity group)

Since, `isSuitableAccess` is used elsewhere as well (e.g., checking for dead ends) this function should probably not be changed to look at potential future floors. However, we could change the `if` in `riskBlocking` to include a check for a planned construction below that can be walked on. 

> The inverse issue sometimes also occurs but is difficult to trigger reliably: [...]

Whenever a construction finishes, `suspendmanager` schedules a cycle for the next tick. So there is the possibility for this happening if both walls get completed in the same tick (or maybe even within 2 ticks). Not sure there is much to be done about this.
