### ISSUE TITLE
seedwatch can't handle pomegranate seeds

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4504]
as per https://discord.com/channels/793331351645323264/807444467140788254/1232210454323925003

**Comment by ab9rf** [comment]
pomegranates are trees, and so pomegranate seeds are tree seeds; seedwatch doesn't do anything for tree seeds because tree seeds are not plantable and so there is no purpose in retaining a stock of them

the reason it reports that "POMEGRANATE has not been found as a material" is because it's looking for a _plant_ named POMEGRANATE, but there is no such plant

so this is WAI except perhaps that seedwatch should simply not mention tree seeds at all since it has nothing useful to say or do about them anyway
