### ISSUE TITLE
creating tame vermin (pets) in gui/create-item results in mangled data

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4507]
as per https://discord.com/channels/793331351645323264/1017471248567124049/1232483204347330631

**Comment by quietust** [comment]
To clarify, the vermin items are somehow ending up with a race of `-1` and a caste consisting of the specified race.

The bug is entirely inside `gui/create-item.lua` and/or `modtools/create-item.lua`, since the `createitem` plugin creates vermin correctly (tested with `createitem VERMIN ANT:QUEEN` and `createitem PET ANT:SOLDIER` and both came out correctly).

**Comment by myk002** [comment]
is it worth replacing logic in `gui/create-item` and/or `modtools/create-item` with a call to `createitem`?

**Comment by quietust** [comment]
They're both calling the same code inside the `Items` module - the only difference is in how they translate user-provided text inputs into numeric IDs.
