### ISSUE TITLE
better error message when using `deathcause` on vermin

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4513]
right now it's a stack trace' should be an explanatory message

**Comment by xBlackTalonX** [comment]
Much better than a stack trace! More minor feedback:
A) Selecting dead vermin within a dump of body parts (unit gui open) and running `deathcause` results in,
"Automatically chose first corpse at selected location. The horse died."

B) Placing the keyboard cursor on that same stack of body parts and running `deathcause` results in,
"deathcause: Please select a corpse"

C) Clicking the stack of body parts beings up a UI screen "item list" (I don't know if there is a common reference to this screen) and then running `deathcause` (with "item list" gui open) results in,
"deathcause: Please select a corpse"

D) Selecting the horse hair item in this list (item gui open),
"The horse died"

E) Selecting an item (toy boat) (item gui open),
"deathcause: Please select a corpse"

F) Selecting a living creature (pig) (unit gui open),
"The pig is not dead yet!"

G) Selecting dead vermin (rat) isolated on a tile (item gui open),
"deathcause: Please select a corpse"

H) Selecting a living creature standing on top of a pile of body parts and vermin (unit gui open),
"[unit] is not dead yet!"

I) Selecting an item (toy boat)(item gui open) in a stack of body parts and living creatures,
"Automatically chose first corpse at selected location. The horse died."

So ideally, 
- B and C should have the result of A: stack of items selected with cursor or gui item list would report that the first corpse in the stack was selected. (or output a line for each item in the stack)
- A (and presumably G) would have the result of D: dead vermin 'remains' would just say, "The [vermin] died," since no further information is really needed to have that limited detail.
- Alternatively, vermin could trigger a message like F, "[vermin] cause of death unsupported" but then that message would seemingly also be appropriate in cases like D (the horse hair).

But this is all really minor stuff so probably not worth more time?

**Comment by myk002** [comment]
done in https://github.com/DFHack/scripts/pull/1095
