### ISSUE TITLE
Missing Codex Titles: Override/Replace string generation logic

### ISSUE THREAD

**Issue by SassyPancakes** [DFHack/dfhack#4584]
Currently a Codex lacks the title of the Writing it bound. This makes buying Codex' to add them to your library a hassle, especially when copy's are made.

- If possible replace string generation logic, so Vanilla UI appears to show the title of the writing
(As already done with the DFHack UI for trade)
(@ Eyeless on Discord for testing, if it gets there)

**Comment by myk002** [comment]
so it looks like there are three cases here:
1. book is an artifact and the artifact has a name
2. book is an artifact and the artifact doesn't have a name
3. book is not an artifact

In case (1), the codex is displayed correctly with a name.
In cases (2) and (3), the codex is displayed as the codex material.

We can fix case (2) with a periodic scan across all artifacts that sets the artifact name to the book title

Case (3) is the tricky one, since there is no place to add a name that will be displayed in lists. We can overwrite the description in this case to fix the list, but then the description will contain text like:

(*«Common Sense Waxing and Waning»*)

This is a Common Sense Waxing and Waning.  It is encircled with bands of round dolomite cabochons.  This object menaces with spikes of well-crafted orpiment.  On the item is a superiorly designed image of forgotten beasts in bloodstone.    The written portion consists of a 139 page manual entitled Common Sense Waxing and Waning, authored by Amala Imazaeci.  It concerns the phases of the moon.  The writing is quite self-indulgent.  Overall, the prose is not awful, but not very good either.    

Which contains awkward repetitions of the title. Compare this to the original:

(*«shale-bound codex»*)

This is a shale-bound codex.  It is encircled with bands of round dolomite cabochons.  This object menaces with spikes of well-crafted orpiment.  On the item is a superiorly designed image of forgotten beasts in bloodstone.    The written portion consists of a 139 page manual entitled Common Sense Waxing and Waning, authored by Amala Imazaeci.  It concerns the phases of the moon.  The writing is quite self-indulgent.  Overall, the prose is not awful, but not very good either.    

so the description replacement does not come without downsides.

**Comment by SassyPancakes** [comment]
Awesome myk002. My gratitude for picking this up, and so fast.
