### ISSUE TITLE
Reverse-engineer surface water feature detection

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#4636]
Plants are categorized into the `shrub_wet` or `tree_wet` vectors if they're within 2 tiles of a surface water feature. Need to figure out this logic for creating plants (`plant` plugin's `plant create`.)

**Comment by quietust** [comment]
The wet/dry distinction is fairly straightforward: it checks a 5x5 region _minus the corners_  around the tile directly beneath the plant, and if at least one of those tiles is a River [Ramp], a Murky Pool [Ramp], a Brook, or a River Source (or a "waterfall from nowhere), then the tile is considered Wet, otherwise it is Dry.

**Comment by Bumber64** [comment]
So that's:
```
MurkyPool
MurkyPoolRamp
Waterfall
RiverSource
BrookN - BrookSE
RiverN - RiverSE
RiverRampN - RiverRampSE
```
But not:
```
BrookTop1 - BrookTop4
```
?
