### ISSUE TITLE
building planner ignores specific material

### ISSUE THREAD

**Issue by Thuztor** [DFHack/dfhack#4731]
One of my modded in building needs adamatine strands.
If you want to build it regular and you have no strands, the game tells you that you need one.
**But if you use DF Hack Planner, you can build it just with every other thread.**

- in short: DF Hack Building Planner ignores certain required building materials, so you can use any material.

Addition: If the player has adamatine strands, they cannot be selected as building material - the list is empty. It only works with "Use closest materials first". Possibly an additional vanilla bug

**Comment by myk002** [comment]
I don't have any mods that use threads for buildings, but I verified this issue with the various weave jobs at a loom. If you're currently using DFHack 50.13-2.1, could you possibly subscribe to the DFHack Steam `testing` branch and confirm if this issue is now fixed for you?

Similarly, if you're currently subscribed to DFHack's `adventure-beta` branch, could you subscribe to `testing-adv-beta`?

**Comment by Thuztor** [comment]
I've tested it with testing-adv-beta and it works as intended!

**Comment by myk002** [comment]
awesome! Thanks!
