### ISSUE TITLE
Idea:  make menus clickable

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#500]
Having to learn DF's many keybindings - or page through menus, and hunt for the key - is a major challenge for new players.  The `mousequery` plugin makes a significant difference by slaving the cursor to the mouse, but it could be better.  Extending the plugin to make menu items clickable, while a non-trivial exercise, would make the game accessible to a much wider range of prospective players.

**Comment by lethosor** [comment]
This isn't really feasible for all menus - many would need to be hardcoded, and any changes that Toady makes to the UI (which are often unannounced) would break individual menus or parts of them, which I don't really think is desirable. Some examples:
* The `b`uilding menu (and its submenus) can contain multiple pages, depending on the window size. The choices are easy to access under `ui_sidebar_menus.building`, but the on-screen positions of each menu item are not.
* The burrows menu is accessible under `ui.burrows`, but is also paginated (and a slightly different size than the building menu)
* Items displayed with loo`k` are accessible under `ui_look_list.items`, but are complicated to access due to the various types of items that can be listed (not all of which are able to be selected). In addition, this menu is paginated using yet another page length, and there is no way to determine the on-screen position of each item without calculating on the page length (which could change at any time, without warning).
Also, there are a number of menus that are already mouse-enabled:
* `d`esignations (excluding submenus)
* `n`obles (including submenus)
If Toady were to add mouse support to more menus without warning, or change existing menus at all, the results would be unpredictable and almost certainly more confusing than simply using keyboard shortcuts.

**Comment by expwnent** [comment]
Maybe if we make it read the text on the screen, so if you click on "t: Chop Down Trees" it simulates the user typing the "t" character, and if they click on "Armor Stand        (a)" then it simulates typing the "a" character. Anything the user can read, DFHack can read.

**Comment by lethosor** [comment]
The biggest problem there is that you'd have to trigger _all_ keys that "t" is bound to, which DFHack doesn't have access to (I'm not sure if the necessary symbol is exported from libgraphics on Linux, and workarounds such as parsing interface.txt or triggering SDL events would take quite a bit of work to handle everything). Also note that HELP, OPTIONS, and MOVIES are handled by DF internally, and not all menus (particularly lists) have keys bound to individual items.

**Comment by expwnent** [comment]
I think that if you change keybindings for actions it updates the screen to the new action. Is that not right?

**Comment by lethosor** [comment]
Yes, but in order to actually trigger it you'd need to feed all DF keycodes bound to that key to the current viewscreen or trigger an SDL event.

**Comment by expwnent** [comment]
I guess I don't understand how DFHack simulates input or the difference between a keycode and a physical key and a character typed, etc. More of a DF internal question than a DFHack question I guess.

**Comment by PeridexisErrant** [comment]
[menu-mouse](http://www.bay12forums.com/smf/index.php?topic=150518) is working on this, and now has a github page.  Worth following, I think.

**Comment by PeridexisErrant** [comment]
The build failure in #750 demonstrates that menu-mouse needs a lot more work, perhaps to the point of needing to start from scratch.  Still, the long desire for better mouse support continues...

**Comment by BenLubar** [comment]
@lethosor @expwnent 

If you type a key in Dwarf Fortress, it fills the `std::set<df::interface_key>` with all of the possible keys already - you can verify this by recording and saving a macro. The viewscreen handles the `df::interface_key`s it understands and ignores the rest.

**Comment by myk002** [comment]
Vanilla DF is now very clickable. some would say too much
