### ISSUE TITLE
fix/stuck-wildlife: try not to poof wildlife that is currently onscreen

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#5123]
maybe require that onscreen wildlife is stuck for a longer time before resorting to poofing to reduce the "huh?" factor for observing players.

**Comment by realSquidCoder** [comment]
Odd idea, but stonesense can follow the df window and show only what's on screen. Perhaps there is code in there to know what's visible to the player and thus what we shouldn't poof? Also, we should probably remember things that were on screen recently so that they also dont poof if we look away for a moment.

**Comment by myk002** [comment]
Figuring what is onscreen isn't that hard of a problem -- the `suspendmanager` overlay is a good example of that, but yes a cooldown timer for visibility might be a good idea
