### ISSUE TITLE
Add TwbT structures research, TwbT

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#615]
Adding the structures used by Mifki's *Text will be Text* plugin would improve compatibility and ease of updating.  [Here's how to find them.](https://github.com/mifki/df-twbt/blob/master/PATCHES.md)

Ultimately, this could lead to importing TwbT as a submodule, or outright addign the code to DFHack.  Mifki has stated that having to find the structures manually is the only barrier to merging, and he's fine with it.

**Comment by lethosor** [comment]
These won't compile at all since `renderer_twbt.h` is not included and SDL_GetKeyState isn't exposed by DFHack portably (and possibly other issues as well).

Given that these plugins' method of detecting TwbT reads from uninitialized memory if TwbT isn't active, and there's no guarantee that the structure of `renderer_twbt` will remain the same, I'd prefer to see some sort of C++ API exposed by TwbT (see #583, mifki/df-twbt#21).

**Comment by PeridexisErrant** [comment]
Made less urgent by #719, but I'll still open an issue over at df-structures.
