### ISSUE TITLE
Add search functionality to the items shown on tiles inspected by 'k' - would be very helpful for QSPs

### ISSUE THREAD

**Issue by pineapplemachine** [DFHack/dfhack#630]

**Comment by lethosor** [comment]
By "items" are you suggesting only what DF considers items or everything listed in the [k] menu? The main issue here is that there are many types of objects that can be displayed in this menu:
``` c
// from generated df/ui_look_list.h
  struct DFHACK_EXPORT ui_look_list {
    struct DFHACK_EXPORT T_items {
      enum T_type : int16_t {
        Item,
        Floor,
        Unit,
        Building,
        Vermin,
        Flow,
        Campfire,
        Spatter,
        BuildingItem,
        Fire,
        Water,
        Magma,
        Spoor
      };
    };
  };
```
Units, items, and possibly vermin and buildings are about the only things for which names are easily obtainable, unless DFHack exposes ways to obtain others that I'm not aware of. I'm thinking of either filtering out types of objects that can't be handled or always displaying them (since there are usually few of the others on a single tile) - thoughts?

**Comment by pineapplemachine** [comment]
I was thinking of everything in the menu, though a profusion of literal items was what prompted me to open the issue. Perhaps when filtering, the ones that are difficult to filter might appear indiscriminately at the end of the list?

**Comment by lethosor** [comment]
Added in #640

**Comment by pineapplemachine** [comment]
Awesome. Thanks!
