### ISSUE TITLE
Travis PR base check hits GitHub rate limit

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#694]
This is the cause of build failures in #692, #693, etc.
The only way around this that I can see is to authenticate to the GitHub API. Travis allows credentials like these to be exposed to scripts as environment variables (and optionally encrypted), but does *not* expose them when building pull requests, since nothing stops someone from modifying the build script to display credentials and making a pull request. Unfortunately, pull requests are exactly what `pr-check-base.py` is intended to check.
Other ideas?

**Comment by expwnent** [comment]
This seems like a problem with github. I'm not sure how to ask them about it but it seems like it would be reasonable to do so.

**Comment by lethosor** [comment]
Now that we're using the container-based infrastructure, we could theoretically cache API results (and/or fetch information for all PRs when we have an API key available and cache that). That wouldn't solve this issue with fresh PRs, but it would for PR builds triggered after the PR has been opened and a non-PR build has been run. Not a great solution, but better than what we have now.
We could also set up an external service that fetches PR information with an API key (and fall back to GitHub's API, of course).

**Comment by PeridexisErrant** [comment]
Until this is properly fixed, how about accepting false negatives instead of false positives?  Most pulls are correctly targeted, it's easy to confirm manually, and getting a red mark when everything should be OK is not a good experience for contributors.

This is as simple as changing the exit code in the `except HTTPError:` block - still print the output, just don't have it fail the build.

**Comment by lethosor** [comment]
Hopefully fixed in aa2ada4cbcfa64467e782f6d7fcf9ebce5712f9d
