### ISSUE TITLE
Old DFHack Files are not Uninstalled

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#695]
If I delete an existing script in the scripts folder then delete it, it will still be there in the hack/ folder. It's not currently an issue but it may later be a problem. The most correct way to do it is to have CMake keep a list of the files installed in the last successful install and delete those before starting a new install (but ideally after confirming that the program builds). I'm pretty sure there are standard solutions to this for CMake but I don't know them.

This is a persnickety issue: it's technically wrong but there are no current important effects.

**Comment by PeridexisErrant** [comment]
Hmm.  The 'correct' behaviour of cleaning before building could also make someone sad that their personal collection of third-party scripts went missing; not a dealbreaker but certainly something to document carefully.

**Comment by expwnent** [comment]
They wouldn't be removed. Subfolders will be removed with rmdir which fails on nonempty folders.

In any case, the safest place for personal scripts is in raw/scripts.

**Comment by warmist** [comment]
I have a ton of custom files everywhere. The scripts folder is symbolic link to dfhack scripts... I think this would not be good...

**Comment by expwnent** [comment]
I meant that it would **not** uninstall custom files. It would only remove old installed files.

**Comment by warmist** [comment]
I don't understand: either you overwrite files while installing or you remove "current installation files". There is no way to track what was "last version installed files" vs "just a quick scratch script for testing".

Imho you are overthinking. Official dfhack installation guide would just ask for clean install (like df asks). If you are messing with files (like all devs are) **they** are ones that know and what to do.

This is a cmake-thing so it's only used by devs. I think they should be proficient enough to understand that installing over it you will have this risk.

I also go this idea that best use would be have it under version control (all the script folders). That is my current use case: the script folder is a symbolic link to git repo of dfhack so all scripts that are tracked are up-to-date all the time. This could be also done if we split the dfhack into scripts+other stuff repos?

**Comment by expwnent** [comment]
If, during installation, CMake makes a file that keeps track of the files installed during that installation, then those can be safely removed the next time it installs over the same directory.

**Comment by warmist** [comment]
Nope: what if i edit it and forget to copy over back into dfhack?

**Comment by expwnent** [comment]
I guess it could check the edit time and see if it was after the last install.

**Comment by warmist** [comment]
Also i question why do you need it? It's very rare (except this case: you are tidying up the scripts currently) that scripts are removed.

**Comment by expwnent** [comment]
It is very rare that it's a problem, but this is a better way of doing it overall. That's what I meant by calling it persnickety.

**Comment by lethosor** [comment]
I'm probably in agreement with warmist here - if you want to ensure a clean installation, you really only have to remove the hack directory and reinstall DFHack.

@expwnent 
> In any case, the safest place for personal scripts is in raw/scripts.

I don't think relying on this as a location for personal scripts is a good idea, since DF will copy them into the save-specific raw folder for every world created after they're added. This makes updating personal scripts that aren't save-specific rather annoying, since you'd have to check every save's raw/scripts folder to ensure consistency. I'd prefer to use a directory outside of raw/ (possibly in hack/, although that would make replacing old DFHack installations slightly more difficult).

@warmist 
> That is my current use case: the script folder is a symbolic link to git repo of dfhack so all scripts that are tracked are up-to-date all the time. This could be also done if we split the dfhack into scripts+other stuff repos?

I'm not sure if this is useful for you, but you can set up another script search directory (instead of using symlinks) with 9eb86c7e38c9c394e26e12e645ba10059ec560de. I haven't implemented commands to do so yet (not sure what good name(s) would be), but I use this in my `dfhack.init`:
```
:lua dfhack.internal.addScriptPath("../dfhack-scripts", true)
```
(If the second argument is truthy, this path will be searched before the default paths)

**Comment by PeridexisErrant** [comment]
FWIW I think that splitting out scripts into a seperate repo could actually be a pretty good idea at this point.  It would certainly help clarify project structure and simplify the build process, which for people working on scripts only is a nightmare at this point.

**Comment by expwnent** [comment]
I guess it's not really important and there are a lot of ways it can go wrong.

The purpose of using raw/scripts is savegame mobility and to help with mod merging.

Maybe an `install-scripts` cmake target? Using that would only require cmake and would help people who are only doing script stuff.
