### ISSUE TITLE
Some plugins could be converted to scripts

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#722]
Scripts do have several advantages over plugins, when the functionality could be performed by either: a clear relationship between command and filename, ease of documentation and de-duplication, limited scope for crashes on error, and better portability across DF versions.

This is not an urgent task, since things are not actually broken at the moment.  I don't expect that all of the plugins listed below will (or even should) be replaced by scripts, but it seems like a good place to start:

- [x] catsplosion
- [x] colonies - see #810
- [x] drybuckets - see also #248
- [x] feature
- [x] fixpositions - to separate fix/diplomats and fix/merchants scripts
- [x] initflags - to separate twaterlvl and tidlers scripts
- [x] weather

The criteria for this list:

- plugins provide one-use commands only (or repeat them regularly, replaceable with the repeat tool)
- reasonably simple to re-implement
- no persistent interaction or GUI elements
- not too much indexing (which is way faster in C++)

**Comment by warmist** [comment]
Things that do a lot of indexing (e.g. lair) need to be in C++ for performance reasons.
Other things like this:
* lair
* fixveins
* fix-unit-occupancy (imho it should not be encorouged to be run auto-repeat, commands like these are FIXES, better to track down stuff that messes stuff up and leave this as sort-of last resort)
* deramp
* cleanedowned (this probably would be very slow in lua)
* regrass

Generally if it is already slow imagine it being 10x slower.

**Comment by PeridexisErrant** [comment]
Hmm, that makes sense - I'll take them off the list.  I'd usually want to measure perf issues, but given that the existing implementation *works* we can just leave well enough alone.

Can I take it you agree in principle with the rest?

**Comment by warmist** [comment]
I agree with the principle. Looking them over and seeing if it's possible (and/or hard) to port is very needed.

I would say we would also gain performance, but in last dfhack versions something takes long even in scripts (do they all get run at startup?)

**Comment by Putnam3145** [comment]
Catsplosion shouldn't be hard for me to remake; it's not the first time I've made a script that forces pregnancy. Heck, I could make any male cats switch to female just so that they can give birth, too.

**Comment by lethosor** [comment]
I agree with most of the current list, except for a few:

* dwarfexport hasn't been supported since 0.40.01, maybe earlier, although it doesn't appear performance-dependent
* cleanconst would be slow in large fortresses if it were written as a script (and since it's most useful in those fortresses, I'm not sure rewriting it is worth it)
* fastdwarf iterates over every unit, every frame, which would be much slower in lua
* flows and tubefill iterate over the entire map, which can be really slow in scripts. changevein would also be slower, although not as much.

@warmist: many "fix" scripts are run on repeat by many users anyway (fix/stuck-doors, fix/build-location, fix/stable-temp, etc., although a few of those are outdated). fix-unit-occupancy doesn't encourage this, as far as I can tell; it just offers it as a possibility (and runs at appropriate times).

From a development perspective, I wouldn't say that scripts are more portable across versions - any structure changes are easy to catch when building plugins that haven't been updated, but it's difficult to test all scripts, let alone each line of every script, so errors often go unnoticed after structure changes.

Regarding filesystem hierarchy, the new `type` command should make it more clear where commands are implemented (although as long as they're in the hack/scripts directory, it is still easier to locate scripts).

**Comment by PeridexisErrant** [comment]
Someone might want to integrate @warmist's script [here](http://www.bay12forums.com/smf/index.php?topic=139553.msg6777104#msg6777104) with a `colonies` port.  I'll get to this eventually if nobody else does.

**Comment by expwnent** [comment]
Catsplosion should probably be removed entirely but I agree with the rest. It's just a matter of doing it.

**Comment by lethosor** [comment]
Why? Doesn't it still work in 0.42?

**Comment by expwnent** [comment]
It works, it's just silly. I don't think anyone uses it.

**Comment by PeridexisErrant** [comment]
I love it - just having `catsplosion` available is a great expression of the attitude the DF community brings!

**Comment by expwnent** [comment]
`petcapRemover` is borderline whether it needs the speed of C++ or not. Since it's borderline I think we should keep it on the C++ side. DFHack FPS impact is a death by a thousand cuts so we should keep things fast when we can.

**Comment by PeridexisErrant** [comment]
Cool, we're down to just two plugins to convert!

@Putnam3145 - do you have the time to provide a `catsplosion` port?

`fixpositions` looks reasonably easy too, but any time I have will go on #794 and #823 first, so anyone else is welcome to take it too :)

**Comment by PeridexisErrant** [comment]
Here's a totally broken prototype:  https://gist.github.com/PeridexisErrant/9b71e093f638d69ecf41

**Comment by lethosor** [comment]
I'm pretty sure `pos.flags.set(entity_position_flags.DO_NOT_CULL)` doesn't work - at the very least, it would need to be changed to `:set()`, but I don't know if that's a defined method.
You probably want `pos.flags.DO_NOT_CULL = true` (you could figure that out by inspecting pos.flags in the lua interpreter, gm-editor, etc. for future reference)

**Comment by PeridexisErrant** [comment]
I was leaving that for after I found the ``entities`` table, becuase ``df.world.entities`` is ``nil`` and without that nothing else is going to work regardless.

**Comment by lethosor** [comment]
Try `df.global.world.entities`

**Comment by lethosor** [comment]
Closing because the fancy checklist is fully checked. I haven't looked around much to see if there are other scripts that would be easy/good to convert, though.
