### ISSUE TITLE
Crash in Search Plugin

### ISSUE THREAD

**Issue by BioLogisch** [DFHack/dfhack#748]
I was searching in the military screen then df crashed:
[dwarfort.exe_2015-11-15-144708_Sinans-iMac.txt](https://github.com/DFHack/dfhack/files/34875/dwarfort.exe_2015-11-15-144708_Sinans-iMac.txt)

I am using this version:
http://www.bay12forums.com/smf/index.php?topic=128960.msg6353416#msg6353416

**Comment by lethosor** [comment]
That version isn't current. Can you try using r4 from this repo?

**Comment by BioLogisch** [comment]
DFHack version 0.40.24-r4 (release)

[dwarfort.exe_2015-11-15-152928_Sinans-iMac.txt](https://github.com/DFHack/dfhack/files/34885/dwarfort.exe_2015-11-15-152928_Sinans-iMac.txt)

Steps to reproduce:
m (military) - c (create squad) - enter - right - right - q - enter a query which does not match any dwarf - enter - enter -> Crash

**Comment by lethosor** [comment]
Oh, that makes sense. The search plugin tries to restore the original list when you press Enter but maintain the unit you have selected (so DF selects the correct unit). It crashes when trying to determine the selected unit when the list is empty, since it assumes the cursor position (0) is always a valid index into the list (which it isn't in this case).

**Comment by lethosor** [comment]
Should be fixed for the next release.
