### ISSUE TITLE
revflood doesn't treat constructed stairs as traversable

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#874]
As a result, running `revflood` will hide any underground areas that are only accessible via constructed stairs. 
[Here](https://www.dropbox.com/s/rxmny07g4c4b2v7/Ganymede.7z?dl=0) is an example save, and this should also be fairly common in generated fortresses (unless they've changed recently).

**Comment by quietust** [comment]
The problem is that worldgen fortress down-stairs are built on top of solid floors rather than open space, and revflood always examines the underlying tile (otherwise it would not reveal beyond a constructed wall, resulting in strange glitches due to the fact that the game does not trigger a Reveal during construction removal).

**Comment by lethosor** [comment]
Interesting. Is it possible that those two are accidentally reversed (in DF)?

Anyway, hopefully it isn't too hard to handle those cases. I'll check on down stairs too, assuming I can find a fort with some.
