### ISSUE TITLE
Include a source code tarball with git submodules included in releases

### ISSUE THREAD

**Issue by TC01** [DFHack/dfhack#892]
It'd be nice if the releases page contained a tarball with all of the git submodules (of which there are [many](https://github.com/DFHack/dfhack/blob/master/.gitmodules)) were included in the release; or at least the ones that compilation depends on.

For those of us who want to build a release of dfhack from source, the [autogenerated tarballs](https://github.com/DFHack/dfhack/archive/0.42.06-alpha2.tar.gz) aren't really usable, since they don't contain the submodules but also aren't a git repository, so it takes a bit of effort to set up the build properly.

**Comment by lethosor** [comment]
DFHack needs to be built in an actual git repository, or it will fail to build when trying to generate version information.

**Comment by TC01** [comment]
Well, in that case, .git should be included with such a tarball as well.

My other agenda for asking this is that I'd like to start building RPM packages of dfhack for Fedora, and it'd be much more convenient if there was a single tarball I could point my spec file at that was officially provided by dfhack upstream. :)

**Comment by lethosor** [comment]
I don't think distributing .git would be a good idea for a couple reasons:
* In the two main clones I have set up, .git is over 130 MB. This is probably more like 100 MB for a fresh clone, but that's still unreasonable to distribute (it's over an order of magnitude larger than the source tarball). Compressing it is unlikely to shrink its size significantly.
* .git is largely a "black box" of sorts - I don't think it's safe to rely on any git version being able to use any .git folder (at least not across different platforms, and providing separate source distributions for all platforms isn't any better)

Anyway, you already need git installed to build DFHack (one step of the build process shells out to git). I'm not familiar with RPM packages at all, but is it really impossible to have a package grab source code from a git repo? Just `git clone --depth=1 --recursive -b master git://github.com/dfhack/dfhack && cd dfhack && git tag some-release-name` would be enough to get DFHack building with minimal space requirements.

One possible solution (on our end) would be to distribute the generated files that contain git information for releases somehow, and alter git-describe.cmake to use those instead of shelling out to git when a specific option is passed to cmake. The issue there is that the file has to contain the current commit ID (and other information), which is somewhat of a challenge to do with git.

**Comment by TC01** [comment]
> In the two main clones I have set up, .git is over 130 MB. This is probably more like 100 MB for a fresh clone, but that's still unreasonable to distribute (it's over an order of magnitude larger than the source tarball). Compressing it is unlikely to shrink its size significantly.

This could be averted by running with ```depth -1```, no? That seems to result (in a brand new clone) of a ```.git``` with size around 4 MB, which is much more reasonable. However:

> .git is largely a "black box" of sorts - I don't think it's safe to rely on any git version being able to use any .git folder (at least not across different platforms, and providing separate source distributions for all platforms isn't any better)

That's a good point, yeah. I certainly know nothing about the structure of a .git directory.

> Anyway, you already need git installed to build DFHack (one step of the build process shells out to git). I'm not familiar with RPM packages at all, but is it really impossible to have a package grab source code from a git repo? Just git clone --depth=1 --recursive -b master git://github.com/dfhack/dfhack && cd dfhack && git tag some-release-name would be enough to get DFHack building with minimal space requirements.

Having git installed as a build dependency isn't the issue; the issue would be downloading additional source code during the package build.

While it would be technically possible (I think) to have a spec file do that, it would be "bad practice"; the Fedora packaging guidelines (and by extension the rpmfusion guidelines, which is likely where a dfhack RPM would end up-- rpmfusion is the biggest "unofficial" Fedora repository of nonfree software or stuff that depends on nonfree software) require that it be possible for packages to be built without an internet connection. 

Having said that, I *could* run those commands myself, tar up the contents, and then pass them to ```rpmbuild``` as the source tarball; that would be fine (or write a small helper script to do it). It'd just be a mild inconvenience to have to remake the tarball every time I go to rebuild the package, which is why I was wondering if this would be a thing dfhack upstream could distribute. 

But it sounds like the simplest solution is probably that I just deal with this downstream when making the package, which is fine. I may be the only person who would actually benefit from these changes anyway. :)

> One possible solution (on our end) would be to distribute the generated files that contain git information for releases somehow, and alter git-describe.cmake to use those instead of shelling out to git when a specific option is passed to cmake. The issue there is that the file has to contain the current commit ID (and other information), which is somewhat of a challenge to do with git.

Possibly this could be done with some kind of push receive hook, or something?  But yes, I agree it would probably be difficult.

**Comment by TC01** [comment]
Just to follow up here, I've written the following script to do this, if anyone else should want it for whatever reason-- build-dfhack-tarball. The resulting tarball can be used to build and install dfhack without network access.

```
#!/bin/bash

# Run this script as "build-dfhack-tarball RELEASE_NAME":

RELEASE_NAME=$1

UPSTREAM="git://github.com/dfhack/dfhack"

# Fetch the repo.
git clone --depth=1 --recursive -b ${RELEASE_NAME} ${UPSTREAM}

# Tarball it up.
tar cfJv dfhack-${RELEASE_NAME}.tar.bz2 dfhack/

# Delete checkout directory.
rm -rfv dfhack/

echo "Done. Wrote dfhack-${RELEASE_NAME}.tar.bz2."
```

(I haven't actually made progress working on a dfhack RPM for Fedora, unfortunately, as I haven't had the time. But I still intend to have a go at it sometime!)

**Comment by TC01** [comment]
> (I haven't actually made progress working on a dfhack RPM for Fedora, unfortunately, as I haven't had the time. But I still intend to have a go at it sometime!)

And by "sometime", I apparently meant "this evening"; there are now functioning (but not yet entirely polished) dfhack packages available [here](https://www.acm.jhu.edu/~bjr/pages/dwarf-fortress-for-fedora.html). :)

This can probably be closed, as the script above is sufficient for my purpose.

**Comment by PeridexisErrant** [comment]
@lethosor - issue closable?

**Comment by lethosor** [comment]
Sure.
